-- Table de formes de noms de pays pour la détection automatique.
-- Mappe les variantes textuelles (anglais, français, codes, abréviations)
-- vers un code ISO 3166-1 alpha-2.

CREATE TABLE IF NOT EXISTS country_name_forms (
    id              SERIAL PRIMARY KEY,
    iso_code        TEXT NOT NULL,           -- ex: "FR", "US", "CN"
    form_normalized TEXT NOT NULL UNIQUE,    -- ex: "france", "usa", "peoples r china"
    created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cnf_iso ON country_name_forms (iso_code);

-- Données initiales : formes les plus courantes dans les adresses
-- Sources : noms anglais, français, codes ISO, variantes WoS/OA
INSERT INTO country_name_forms (iso_code, form_normalized) VALUES
-- Europe occidentale
('FR', 'france'), ('FR', 'france.'), ('FR', 'fra'), ('FR', 'francia'),
('DE', 'germany'), ('DE', 'allemagne'), ('DE', 'deutschland'), ('DE', 'fed rep ger'),
('GB', 'uk'), ('GB', 'united kingdom'), ('GB', 'england'), ('GB', 'scotland'), ('GB', 'wales'), ('GB', 'great britain'), ('GB', 'royaume-uni'), ('GB', 'royaume uni'),
('IT', 'italy'), ('IT', 'italie'), ('IT', 'italia'),
('ES', 'spain'), ('ES', 'espagne'), ('ES', 'espana'),
('PT', 'portugal'),
('NL', 'netherlands'), ('NL', 'the netherlands'), ('NL', 'pays-bas'), ('NL', 'pays bas'), ('NL', 'holland'),
('BE', 'belgium'), ('BE', 'belgique'), ('BE', 'belgie'),
('LU', 'luxembourg'),
('CH', 'switzerland'), ('CH', 'suisse'), ('CH', 'schweiz'),
('AT', 'austria'), ('AT', 'autriche'), ('AT', 'osterreich'),
('IE', 'ireland'), ('IE', 'irlande'),
('MC', 'monaco'),
-- Scandinavie
('SE', 'sweden'), ('SE', 'suede'),
('NO', 'norway'), ('NO', 'norvege'),
('DK', 'denmark'), ('DK', 'danemark'),
('FI', 'finland'), ('FI', 'finlande'),
('IS', 'iceland'), ('IS', 'islande'),
-- Europe centrale et orientale
('PL', 'poland'), ('PL', 'pologne'), ('PL', 'polska'),
('CZ', 'czech republic'), ('CZ', 'czechia'), ('CZ', 'republique tcheque'),
('SK', 'slovakia'), ('SK', 'slovaquie'),
('HU', 'hungary'), ('HU', 'hongrie'),
('RO', 'romania'), ('RO', 'roumanie'),
('BG', 'bulgaria'), ('BG', 'bulgarie'),
('HR', 'croatia'), ('HR', 'croatie'),
('SI', 'slovenia'), ('SI', 'slovenie'),
('RS', 'serbia'), ('RS', 'serbie'),
('BA', 'bosnia and herzegovina'), ('BA', 'bosnia & herzegovina'), ('BA', 'bosnie'),
('ME', 'montenegro'),
('MK', 'north macedonia'), ('MK', 'macedonia'),
('AL', 'albania'), ('AL', 'albanie'),
('EE', 'estonia'), ('EE', 'estonie'),
('LV', 'latvia'), ('LV', 'lettonie'),
('LT', 'lithuania'), ('LT', 'lituanie'),
-- Europe du Sud-Est / Méditerranée
('GR', 'greece'), ('GR', 'grece'),
('TR', 'turkey'), ('TR', 'turquie'), ('TR', 'turkiye'),
('CY', 'cyprus'), ('CY', 'chypre'),
('MT', 'malta'), ('MT', 'malte'),
-- Ex-URSS
('RU', 'russia'), ('RU', 'russie'), ('RU', 'russian federation'),
('UA', 'ukraine'),
('BY', 'belarus'),
('MD', 'moldova'),
('GE', 'georgia'),
('AM', 'armenia'), ('AM', 'armenie'),
('AZ', 'azerbaijan'), ('AZ', 'azerbaidjan'),
('KZ', 'kazakhstan'),
('UZ', 'uzbekistan'), ('UZ', 'ouzbekistan'),
-- Amérique du Nord
('US', 'usa'), ('US', 'united states'), ('US', 'united states of america'), ('US', 'u.s.a.'), ('US', 'u.s.a'), ('US', 'etats-unis'), ('US', 'etats unis'),
('CA', 'canada'),
('MX', 'mexico'), ('MX', 'mexique'),
-- Amérique du Sud
('BR', 'brazil'), ('BR', 'bresil'), ('BR', 'brasil'),
('AR', 'argentina'), ('AR', 'argentine'),
('CL', 'chile'), ('CL', 'chili'),
('CO', 'colombia'), ('CO', 'colombie'),
('PE', 'peru'), ('PE', 'perou'),
('VE', 'venezuela'),
('EC', 'ecuador'), ('EC', 'equateur'),
('UY', 'uruguay'),
('PY', 'paraguay'),
('BO', 'bolivia'), ('BO', 'bolivie'),
-- Amérique centrale et Caraïbes
('CR', 'costa rica'),
('PA', 'panama'),
('CU', 'cuba'),
('GT', 'guatemala'),
('HN', 'honduras'),
('SV', 'el salvador'),
('NI', 'nicaragua'),
('JM', 'jamaica'), ('JM', 'jamaique'),
('HT', 'haiti'),
('DO', 'dominican republic'), ('DO', 'republique dominicaine'),
('TT', 'trinidad and tobago'),
('PR', 'puerto rico'), ('PR', 'porto rico'),
-- Asie de l'Est
('CN', 'china'), ('CN', 'chine'), ('CN', 'peoples r china'), ('CN', 'p.r. china'), ('CN', 'pr china'),
('JP', 'japan'), ('JP', 'japon'),
('KR', 'south korea'), ('KR', 'korea'), ('KR', 'coree du sud'), ('KR', 'republic of korea'),
('KP', 'north korea'), ('KP', 'coree du nord'),
('TW', 'taiwan'),
('MN', 'mongolia'), ('MN', 'mongolie'),
-- Asie du Sud-Est
('VN', 'vietnam'), ('VN', 'viet nam'),
('TH', 'thailand'), ('TH', 'thailande'),
('MY', 'malaysia'), ('MY', 'malaisie'),
('SG', 'singapore'), ('SG', 'singapour'),
('ID', 'indonesia'), ('ID', 'indonesie'),
('PH', 'philippines'),
('MM', 'myanmar'),
('KH', 'cambodia'), ('KH', 'cambodge'),
('LA', 'laos'),
-- Asie du Sud
('IN', 'india'), ('IN', 'inde'),
('PK', 'pakistan'),
('BD', 'bangladesh'),
('LK', 'sri lanka'),
('NP', 'nepal'),
-- Moyen-Orient
('IL', 'israel'),
('LB', 'lebanon'), ('LB', 'liban'),
('JO', 'jordan'), ('JO', 'jordanie'),
('IQ', 'iraq'), ('IQ', 'irak'),
('IR', 'iran'),
('SA', 'saudi arabia'), ('SA', 'arabie saoudite'),
('AE', 'united arab emirates'), ('AE', 'uae'), ('AE', 'emirats arabes unis'),
('QA', 'qatar'),
('KW', 'kuwait'), ('KW', 'koweit'),
('OM', 'oman'),
('BH', 'bahrain'),
('PS', 'palestine'),
('SY', 'syria'), ('SY', 'syrie'),
('YE', 'yemen'),
-- Afrique du Nord
('MA', 'morocco'), ('MA', 'maroc'),
('DZ', 'algeria'), ('DZ', 'algerie'),
('TN', 'tunisia'), ('TN', 'tunisie'),
('EG', 'egypt'), ('EG', 'egypte'),
('LY', 'libya'), ('LY', 'libye'),
-- Afrique subsaharienne
('ZA', 'south africa'), ('ZA', 'afrique du sud'),
('NG', 'nigeria'),
('KE', 'kenya'),
('ET', 'ethiopia'), ('ET', 'ethiopie'),
('GH', 'ghana'),
('SN', 'senegal'),
('CI', 'ivory coast'), ('CI', 'cote d''ivoire'), ('CI', 'cote divoire'),
('CM', 'cameroon'), ('CM', 'cameroun'),
('TZ', 'tanzania'), ('TZ', 'tanzanie'),
('UG', 'uganda'), ('UG', 'ouganda'),
('MG', 'madagascar'),
('CD', 'democratic republic of the congo'), ('CD', 'dr congo'), ('CD', 'rdc'),
('CG', 'republic of the congo'), ('CG', 'congo'),
('BF', 'burkina faso'),
('ML', 'mali'),
('NE', 'niger'),
('BJ', 'benin'),
('TD', 'chad'), ('TD', 'tchad'),
('RW', 'rwanda'),
('MZ', 'mozambique'),
('ZW', 'zimbabwe'),
('MU', 'mauritius'), ('MU', 'maurice'),
('GA', 'gabon'),
('TG', 'togo'),
-- Océanie
('AU', 'australia'), ('AU', 'australie'),
('NZ', 'new zealand'), ('NZ', 'nouvelle-zelande'), ('NZ', 'nouvelle zelande'),
('FJ', 'fiji'), ('FJ', 'fidji'),
('NC', 'new caledonia'), ('NC', 'nouvelle-caledonie'), ('NC', 'nouvelle caledonie'),
('PF', 'french polynesia'), ('PF', 'polynesie francaise'),
-- Territoires français d'outre-mer (mappés vers FR)
('FR', 'guadeloupe'), ('FR', 'martinique'), ('FR', 'guyane'), ('FR', 'reunion'), ('FR', 'mayotte'),
('FR', 'la reunion'), ('FR', 'guyane francaise'), ('FR', 'french guiana')
ON CONFLICT (form_normalized) DO NOTHING;
