"""person_name_forms : dénormalisation `persons jsonb` → table simple (name_form, person_id, sources[])

La contrainte `UNIQUE (name_form)` historique avait imposé un JSONB
`{"<pid>": ["<source>", ...]}` pour porter le mapping nom → personnes
sans dupliquer le texte. Avec PK composite `(name_form, person_id)` la
relation many-to-many s'exprime naturellement en rows, sans JSONB.

Disparaissent :
- colonne `persons jsonb` + CHECK `persons_not_empty` + index GIN
- contrainte `UNIQUE (name_form)`
- colonnes `id` + sequence + `created_at` + `updated_at`
  (la table dénormalisée n'a plus de propriétés propres à dater)

Apparaît :
- `person_id integer NOT NULL REFERENCES persons(id) ON DELETE CASCADE`
- `sources text[] NOT NULL DEFAULT '{}'`
- PK `(name_form, person_id)` + index B-tree sur `person_id`

Backfill : un row par couple (name_form, person_id) du JSONB, sources
agrégées via `jsonb_array_elements_text` triées.

Revision ID: 0016
Revises: 0015
Create Date: 2026-05-16 15:00:00.000000
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0016"
down_revision: str | Sequence[str] | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Décomposer le JSONB en triplets en table temp, puis recréer la
    # table cible vide et la repopuler — c'est plus simple et plus
    # lisible qu'un ALTER en place (5 colonnes touchées).
    op.execute(
        """
        CREATE TEMP TABLE _pnf_decomposed AS
        SELECT
            o.name_form,
            (k.key)::int AS person_id,
            COALESCE(
                ARRAY(
                    SELECT s
                    FROM jsonb_array_elements_text(o.persons->k.key) AS s
                    ORDER BY s
                ),
                '{}'::text[]
            ) AS sources
        FROM person_name_forms o,
             LATERAL jsonb_object_keys(o.persons) AS k(key)
        """
    )
    op.execute("DROP TABLE person_name_forms")
    op.execute(
        """
        CREATE TABLE person_name_forms (
            name_form text NOT NULL,
            person_id integer NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
            sources text[] NOT NULL DEFAULT '{}',
            PRIMARY KEY (name_form, person_id)
        )
        """
    )
    op.execute("CREATE INDEX idx_pnf_person_id ON person_name_forms (person_id)")
    op.execute(
        """
        INSERT INTO person_name_forms (name_form, person_id, sources)
        SELECT name_form, person_id, sources FROM _pnf_decomposed
        """
    )
    op.execute("DROP TABLE _pnf_decomposed")


def downgrade() -> None:
    # Reconstitue le JSONB depuis les triplets puis remonte la
    # structure historique (id, UNIQUE, CHECK, GIN, dates).
    op.execute(
        """
        CREATE TEMP TABLE _pnf_recomposed AS
        SELECT name_form,
               jsonb_object_agg(person_id::text, to_jsonb(sources)) AS persons
        FROM person_name_forms
        GROUP BY name_form
        """
    )
    op.execute("DROP TABLE person_name_forms")
    op.execute(
        """
        CREATE TABLE person_name_forms (
            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name_form text NOT NULL,
            created_at timestamp with time zone DEFAULT now(),
            updated_at timestamp with time zone DEFAULT now(),
            persons jsonb NOT NULL,
            CONSTRAINT persons_not_empty CHECK (persons <> '{}'::jsonb),
            CONSTRAINT person_name_forms_name_form_uq UNIQUE (name_form)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX idx_pnf_persons_gin
        ON person_name_forms USING gin (persons jsonb_path_ops)
        """
    )
    op.execute(
        """
        INSERT INTO person_name_forms (name_form, persons)
        SELECT name_form, persons FROM _pnf_recomposed
        """
    )
    op.execute("DROP TABLE _pnf_recomposed")
