"""drop staging.meta_hash

Revision ID: fc06f11bd3e0
Revises: 0021
Create Date: 2026-05-20 07:48:31.995024

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc06f11bd3e0"
down_revision: str | Sequence[str] | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_addresses_normalized_text"), table_name="addresses")
    op.drop_index(
        op.f("idx_source_docs_countries"),
        table_name="source_publications",
        postgresql_using="gin",
        postgresql_where="(countries IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_source_docs_doi"),
        table_name="source_publications",
        postgresql_where="(doi IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_source_docs_external_ids"),
        table_name="source_publications",
        postgresql_using="gin",
        postgresql_where="(external_ids IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_source_docs_hal_collections"),
        table_name="source_publications",
        postgresql_using="gin",
        postgresql_where="(hal_collections IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_source_docs_pub"),
        table_name="source_publications",
        postgresql_where="(publication_id IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_source_docs_staging"),
        table_name="source_publications",
        postgresql_where="(staging_id IS NOT NULL)",
    )
    op.create_index(
        "idx_source_pubs_countries",
        "source_publications",
        ["countries"],
        unique=False,
        postgresql_using="gin",
        postgresql_where=sa.text("countries IS NOT NULL"),
    )
    op.create_index(
        "idx_source_pubs_doi",
        "source_publications",
        ["doi"],
        unique=False,
        postgresql_where=sa.text("doi IS NOT NULL"),
    )
    op.create_index(
        "idx_source_pubs_external_ids",
        "source_publications",
        ["external_ids"],
        unique=False,
        postgresql_using="gin",
        postgresql_where=sa.text("external_ids IS NOT NULL"),
    )
    op.create_index(
        "idx_source_pubs_hal_collections",
        "source_publications",
        ["hal_collections"],
        unique=False,
        postgresql_using="gin",
        postgresql_where=sa.text("hal_collections IS NOT NULL"),
    )
    op.create_index(
        "idx_source_pubs_pub",
        "source_publications",
        ["publication_id"],
        unique=False,
        postgresql_where=sa.text("publication_id IS NOT NULL"),
    )
    op.create_index(
        "idx_source_pubs_staging",
        "source_publications",
        ["staging_id"],
        unique=False,
        postgresql_where=sa.text("staging_id IS NOT NULL"),
    )
    op.alter_column(
        "staging",
        "raw_hash",
        existing_type=sa.TEXT(),
        comment="Empreinte md5 du payload tel qu'extrait de la source bulk. Sert de clé de détection de changement à l'UPSERT (et d'empreinte d'intégrité pour le chantier DATA_raw-data-store). Cas particulier OpenAlex : `refetch_truncated` n'écrit PAS `raw_hash` quand il complète les authorships d'une publication tronquée à 100 — la ligne garde le hash du payload bulk pour que le bulk suivant ne déclenche pas de réécriture inutile. L'invariant `raw_hash = md5(raw_data)` est donc volontairement rompu sur les lignes OpenAlex refetchées.",
        existing_nullable=True,
    )
    op.drop_column("staging", "meta_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("staging", sa.Column("meta_hash", sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column(
        "staging",
        "raw_hash",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Empreinte md5 du payload tel qu'extrait de la source bulk. Sert de clé de détection de changement à l'UPSERT (et d'empreinte d'intégrité pour le chantier DATA_raw-data-store). Cas particulier OpenAlex : `refetch_truncated` n'écrit PAS `raw_hash` quand il complète les authorships d'une publication tronquée à 100 — la ligne garde le hash du payload bulk pour que le bulk suivant ne déclenche pas de réécriture inutile. L'invariant `raw_hash = md5(raw_data)` est donc volontairement rompu sur les lignes OpenAlex refetchées.",
        existing_nullable=True,
    )
    op.drop_index(
        "idx_source_pubs_staging",
        table_name="source_publications",
        postgresql_where=sa.text("staging_id IS NOT NULL"),
    )
    op.drop_index(
        "idx_source_pubs_pub",
        table_name="source_publications",
        postgresql_where=sa.text("publication_id IS NOT NULL"),
    )
    op.drop_index(
        "idx_source_pubs_hal_collections",
        table_name="source_publications",
        postgresql_using="gin",
        postgresql_where=sa.text("hal_collections IS NOT NULL"),
    )
    op.drop_index(
        "idx_source_pubs_external_ids",
        table_name="source_publications",
        postgresql_using="gin",
        postgresql_where=sa.text("external_ids IS NOT NULL"),
    )
    op.drop_index(
        "idx_source_pubs_doi",
        table_name="source_publications",
        postgresql_where=sa.text("doi IS NOT NULL"),
    )
    op.drop_index(
        "idx_source_pubs_countries",
        table_name="source_publications",
        postgresql_using="gin",
        postgresql_where=sa.text("countries IS NOT NULL"),
    )
    op.create_index(
        op.f("idx_source_docs_staging"),
        "source_publications",
        ["staging_id"],
        unique=False,
        postgresql_where="(staging_id IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_source_docs_pub"),
        "source_publications",
        ["publication_id"],
        unique=False,
        postgresql_where="(publication_id IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_source_docs_hal_collections"),
        "source_publications",
        ["hal_collections"],
        unique=False,
        postgresql_using="gin",
        postgresql_where="(hal_collections IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_source_docs_external_ids"),
        "source_publications",
        ["external_ids"],
        unique=False,
        postgresql_using="gin",
        postgresql_where="(external_ids IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_source_docs_doi"),
        "source_publications",
        ["doi"],
        unique=False,
        postgresql_where="(doi IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_source_docs_countries"),
        "source_publications",
        ["countries"],
        unique=False,
        postgresql_using="gin",
        postgresql_where="(countries IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_addresses_normalized_text"), "addresses", ["normalized_text"], unique=False
    )
    # ### end Alembic commands ###
