"""drop staging.meta_hash

Revision ID: fc06f11bd3e0
Revises: 0021
Create Date: 2026-05-20 07:48:31.995024

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc06f11bd3e0"
down_revision: str | Sequence[str] | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "staging",
        "raw_hash",
        existing_type=sa.TEXT(),
        comment="Empreinte md5 du payload tel qu'extrait de la source bulk. Sert de clé de détection de changement à l'UPSERT (et d'empreinte d'intégrité pour le chantier DATA_raw-data-store). Cas particulier OpenAlex : `refetch_truncated` n'écrit PAS `raw_hash` quand il complète les authorships d'une publication tronquée à 100 — la ligne garde le hash du payload bulk pour que le bulk suivant ne déclenche pas de réécriture inutile. L'invariant `raw_hash = md5(raw_data)` est donc volontairement rompu sur les lignes OpenAlex refetchées.",
        existing_nullable=True,
    )
    op.drop_column("staging", "meta_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("staging", sa.Column("meta_hash", sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column(
        "staging",
        "raw_hash",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Empreinte md5 du payload tel qu'extrait de la source bulk. Sert de clé de détection de changement à l'UPSERT (et d'empreinte d'intégrité pour le chantier DATA_raw-data-store). Cas particulier OpenAlex : `refetch_truncated` n'écrit PAS `raw_hash` quand il complète les authorships d'une publication tronquée à 100 — la ligne garde le hash du payload bulk pour que le bulk suivant ne déclenche pas de réécriture inutile. L'invariant `raw_hash = md5(raw_data)` est donc volontairement rompu sur les lignes OpenAlex refetchées.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
