"""Tables languages et language_forms : référentiel des langues

`languages` porte une ligne par langue : code ISO 639-1, ou ISO 639-3 pour une langue qui n'a pas de code à deux lettres, et nom français. `language_forms` porte, en minuscules, les formes sous lesquelles les sources désignent une langue : son code, ses codes ISO 639-3 et ISO 639-2 bibliographique, son nom anglais. Les données viennent des tables ISO 639 de pycountry ; quelques noms français sont revus.

Revision ID: c5e8a1f2d937
Revises: a7d3e51c9b84
Create Date: 2026-09-14 10:00:00.000000
"""

from collections.abc import Sequence

from alembic import op

revision: str = "c5e8a1f2d937"
down_revision: str | Sequence[str] | None = "a7d3e51c9b84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_UPGRADE = """
CREATE TABLE public.languages (
    code text PRIMARY KEY,
    name text NOT NULL
);

COMMENT ON TABLE public.languages IS 'Référentiel des langues. code : ISO 639-1, ou ISO 639-3 pour une langue sans code à deux lettres. name : nom français, affiché.';

CREATE TABLE public.language_forms (
    form_normalized text PRIMARY KEY,
    language_code text NOT NULL REFERENCES public.languages (code) ON DELETE CASCADE
);

COMMENT ON TABLE public.language_forms IS 'Formes sous lesquelles les sources désignent une langue, en minuscules : codes à deux et trois lettres, nom anglais.';

INSERT INTO public.languages (code, name) VALUES
    ('aa', 'Afar'),
    ('ab', 'Abkhaze'),
    ('ae', 'Avestique'),
    ('af', 'Afrikaans'),
    ('ak', 'Akan'),
    ('am', 'Amharique'),
    ('an', 'Aragonais'),
    ('ang', 'Vieil anglais'),
    ('ar', 'Arabe'),
    ('as', 'Assamais'),
    ('av', 'Avar'),
    ('ay', 'Aymara'),
    ('az', 'Azéri'),
    ('ba', 'Bachkir'),
    ('be', 'Biélorusse'),
    ('bg', 'Bulgare'),
    ('bi', 'Bichelamar'),
    ('bm', 'Bambara'),
    ('bn', 'Bengali'),
    ('bo', 'Tibétain'),
    ('br', 'Breton'),
    ('bs', 'Bosniaque'),
    ('ca', 'Catalan'),
    ('ce', 'Tchétchène'),
    ('ceb', 'Cebuano'),
    ('ch', 'Chamorro'),
    ('ckb', 'Kurde central'),
    ('co', 'Corse'),
    ('cr', 'Cri'),
    ('cs', 'Tchèque'),
    ('cu', 'Slavon d''Église'),
    ('cv', 'Tchouvache'),
    ('cy', 'Gallois'),
    ('da', 'Danois'),
    ('de', 'Allemand'),
    ('dv', 'Divehi'),
    ('dz', 'Dzongkha'),
    ('ee', 'Éwé'),
    ('el', 'Grec moderne'),
    ('en', 'Anglais'),
    ('eo', 'Espéranto'),
    ('es', 'Espagnol'),
    ('et', 'Estonien'),
    ('eu', 'Basque'),
    ('fa', 'Persan'),
    ('ff', 'Peul'),
    ('fi', 'Finnois'),
    ('fj', 'Fidjien'),
    ('fo', 'Féroïen'),
    ('fr', 'Français'),
    ('fy', 'Frison occidental'),
    ('ga', 'Irlandais'),
    ('gd', 'Gaélique écossais'),
    ('gl', 'Galicien'),
    ('gn', 'Guarani'),
    ('grc', 'Grec ancien'),
    ('gu', 'Goudjarati'),
    ('gv', 'Mannois'),
    ('ha', 'Haoussa'),
    ('he', 'Hébreu'),
    ('hi', 'Hindi'),
    ('ho', 'Hiri Motu'),
    ('hr', 'Croate'),
    ('ht', 'Créole haïtien'),
    ('hu', 'Hongrois'),
    ('hy', 'Arménien'),
    ('hz', 'Herero'),
    ('ia', 'Interlingua'),
    ('id', 'Indonésien'),
    ('ie', 'Interlingue'),
    ('ig', 'Igbo'),
    ('ii', 'Yi de Sichuan'),
    ('ik', 'Inupiaq'),
    ('io', 'Ido'),
    ('is', 'Islandais'),
    ('it', 'Italien'),
    ('iu', 'Inuktitut'),
    ('ja', 'Japonais'),
    ('jv', 'Javanais'),
    ('ka', 'Géorgien'),
    ('kg', 'Kongo'),
    ('ki', 'Kikuyu'),
    ('kj', 'Kuanyama'),
    ('kk', 'Kazakh'),
    ('kl', 'Kalaallisut'),
    ('km', 'Khmer'),
    ('kn', 'Kannada'),
    ('ko', 'Coréen'),
    ('kr', 'Kanouri'),
    ('ks', 'Kashmiri'),
    ('ku', 'Kurde'),
    ('kv', 'Komi'),
    ('kw', 'Cornique'),
    ('ky', 'Kirghize'),
    ('la', 'Latin'),
    ('lb', 'Luxembourgeois'),
    ('lg', 'Ganda'),
    ('li', 'Limbourgeois'),
    ('ln', 'Lingala'),
    ('lo', 'Laotien'),
    ('lt', 'Lituanien'),
    ('lu', 'Luba-katanga'),
    ('lv', 'Letton'),
    ('mg', 'Malgache'),
    ('mh', 'Marshallais'),
    ('mi', 'Maori'),
    ('mk', 'Macédonien'),
    ('ml', 'Malayalam'),
    ('mn', 'Mongol'),
    ('mr', 'Marathe'),
    ('ms', 'Malais'),
    ('mt', 'Maltais'),
    ('my', 'Birman'),
    ('na', 'Nauru'),
    ('nb', 'Norvégien bokmål'),
    ('nd', 'Ndebele septentrional'),
    ('ne', 'Népalais'),
    ('ng', 'Ndonga'),
    ('nl', 'Néerlandais'),
    ('nn', 'Norvégien nynorsk'),
    ('no', 'Norvégien'),
    ('nr', 'Ndebele méridional'),
    ('nv', 'Navajo'),
    ('ny', 'Chichewa'),
    ('oc', 'Occitan'),
    ('oj', 'Ojibwa'),
    ('om', 'Oromo'),
    ('or', 'Oriya'),
    ('os', 'Ossétien'),
    ('pa', 'Pendjabi'),
    ('pi', 'Pali'),
    ('pl', 'Polonais'),
    ('ps', 'Pachto'),
    ('pt', 'Portugais'),
    ('qu', 'Quechua'),
    ('rm', 'Romanche'),
    ('rn', 'Rundi'),
    ('ro', 'Roumain'),
    ('ru', 'Russe'),
    ('rw', 'Kinyarwanda'),
    ('sa', 'Sanskrit'),
    ('sc', 'Sarde'),
    ('sd', 'Sindhi'),
    ('se', 'Sami du Nord'),
    ('sg', 'Sango'),
    ('sh', 'Serbo-croate'),
    ('si', 'Singhalais'),
    ('sk', 'Slovaque'),
    ('sl', 'Slovène'),
    ('sm', 'Samoan'),
    ('sn', 'Shona'),
    ('so', 'Somali'),
    ('sq', 'Albanais'),
    ('sr', 'Serbe'),
    ('ss', 'Swati'),
    ('st', 'Sotho méridional'),
    ('su', 'Sundanais'),
    ('sv', 'Suédois'),
    ('sw', 'Swahili'),
    ('ta', 'Tamoul'),
    ('te', 'Télougou'),
    ('tg', 'Tadjik'),
    ('th', 'Thaï'),
    ('ti', 'Tigrigna'),
    ('tk', 'Turkmène'),
    ('tl', 'Tagalog'),
    ('tn', 'Tswana'),
    ('to', 'Tongien'),
    ('tr', 'Turc'),
    ('ts', 'Tsonga'),
    ('tt', 'Tatar'),
    ('tw', 'Twi'),
    ('ty', 'Tahitien'),
    ('ug', 'Ouïghour'),
    ('uk', 'Ukrainien'),
    ('ur', 'Ourdou'),
    ('uz', 'Ouzbek'),
    ('ve', 'Venda'),
    ('vi', 'Vietnamien'),
    ('vo', 'Volapük'),
    ('wa', 'Wallon'),
    ('wo', 'Wolof'),
    ('xh', 'Xhosa'),
    ('yi', 'Yiddish'),
    ('yo', 'Yoruba'),
    ('za', 'Zhuang'),
    ('zh', 'Chinois'),
    ('zu', 'Zoulou');

INSERT INTO public.language_forms (form_normalized, language_code) VALUES
    ('aa', 'aa'),
    ('aar', 'aa'),
    ('afar', 'aa'),
    ('ab', 'ab'),
    ('abk', 'ab'),
    ('abkhazian', 'ab'),
    ('ae', 'ae'),
    ('ave', 'ae'),
    ('avestan', 'ae'),
    ('af', 'af'),
    ('afr', 'af'),
    ('afrikaans', 'af'),
    ('ak', 'ak'),
    ('aka', 'ak'),
    ('akan', 'ak'),
    ('am', 'am'),
    ('amh', 'am'),
    ('amharic', 'am'),
    ('an', 'an'),
    ('aragonese', 'an'),
    ('arg', 'an'),
    ('ang', 'ang'),
    ('old english', 'ang'),
    ('ar', 'ar'),
    ('ara', 'ar'),
    ('arabic', 'ar'),
    ('as', 'as'),
    ('asm', 'as'),
    ('assamese', 'as'),
    ('av', 'av'),
    ('ava', 'av'),
    ('avaric', 'av'),
    ('ay', 'ay'),
    ('aym', 'ay'),
    ('aymara', 'ay'),
    ('az', 'az'),
    ('aze', 'az'),
    ('azerbaijani', 'az'),
    ('ba', 'ba'),
    ('bak', 'ba'),
    ('bashkir', 'ba'),
    ('be', 'be'),
    ('bel', 'be'),
    ('belarusian', 'be'),
    ('bg', 'bg'),
    ('bul', 'bg'),
    ('bulgarian', 'bg'),
    ('bi', 'bi'),
    ('bis', 'bi'),
    ('bislama', 'bi'),
    ('bam', 'bm'),
    ('bambara', 'bm'),
    ('bm', 'bm'),
    ('ben', 'bn'),
    ('bengali', 'bn'),
    ('bn', 'bn'),
    ('bo', 'bo'),
    ('bod', 'bo'),
    ('tib', 'bo'),
    ('tibetan', 'bo'),
    ('br', 'br'),
    ('bre', 'br'),
    ('breton', 'br'),
    ('bos', 'bs'),
    ('bosnian', 'bs'),
    ('bs', 'bs'),
    ('ca', 'ca'),
    ('cat', 'ca'),
    ('catalan', 'ca'),
    ('ce', 'ce'),
    ('che', 'ce'),
    ('chechen', 'ce'),
    ('ceb', 'ceb'),
    ('cebuano', 'ceb'),
    ('ch', 'ch'),
    ('cha', 'ch'),
    ('chamorro', 'ch'),
    ('central kurdish', 'ckb'),
    ('ckb', 'ckb'),
    ('co', 'co'),
    ('corsican', 'co'),
    ('cos', 'co'),
    ('cr', 'cr'),
    ('cre', 'cr'),
    ('cree', 'cr'),
    ('ces', 'cs'),
    ('cs', 'cs'),
    ('cze', 'cs'),
    ('czech', 'cs'),
    ('chu', 'cu'),
    ('church slavic', 'cu'),
    ('cu', 'cu'),
    ('chuvash', 'cv'),
    ('chv', 'cv'),
    ('cv', 'cv'),
    ('cy', 'cy'),
    ('cym', 'cy'),
    ('wel', 'cy'),
    ('welsh', 'cy'),
    ('da', 'da'),
    ('dan', 'da'),
    ('danish', 'da'),
    ('de', 'de'),
    ('deu', 'de'),
    ('ger', 'de'),
    ('german', 'de'),
    ('div', 'dv'),
    ('divehi', 'dv'),
    ('dv', 'dv'),
    ('dz', 'dz'),
    ('dzo', 'dz'),
    ('dzongkha', 'dz'),
    ('ee', 'ee'),
    ('ewe', 'ee'),
    ('el', 'el'),
    ('ell', 'el'),
    ('gre', 'el'),
    ('greek', 'el'),
    ('modern greek', 'el'),
    ('en', 'en'),
    ('eng', 'en'),
    ('english', 'en'),
    ('eo', 'eo'),
    ('epo', 'eo'),
    ('esperanto', 'eo'),
    ('es', 'es'),
    ('spa', 'es'),
    ('spanish', 'es'),
    ('est', 'et'),
    ('estonian', 'et'),
    ('et', 'et'),
    ('baq', 'eu'),
    ('basque', 'eu'),
    ('eu', 'eu'),
    ('eus', 'eu'),
    ('fa', 'fa'),
    ('fas', 'fa'),
    ('per', 'fa'),
    ('persian', 'fa'),
    ('ff', 'ff'),
    ('ful', 'ff'),
    ('fulah', 'ff'),
    ('fi', 'fi'),
    ('fin', 'fi'),
    ('finnish', 'fi'),
    ('fij', 'fj'),
    ('fijian', 'fj'),
    ('fj', 'fj'),
    ('fao', 'fo'),
    ('faroese', 'fo'),
    ('fo', 'fo'),
    ('fr', 'fr'),
    ('fra', 'fr'),
    ('fre', 'fr'),
    ('french', 'fr'),
    ('fry', 'fy'),
    ('fy', 'fy'),
    ('western frisian', 'fy'),
    ('ga', 'ga'),
    ('gle', 'ga'),
    ('irish', 'ga'),
    ('gd', 'gd'),
    ('gla', 'gd'),
    ('scottish gaelic', 'gd'),
    ('galician', 'gl'),
    ('gl', 'gl'),
    ('glg', 'gl'),
    ('gn', 'gn'),
    ('grn', 'gn'),
    ('guarani', 'gn'),
    ('ancient greek', 'grc'),
    ('grc', 'grc'),
    ('gu', 'gu'),
    ('guj', 'gu'),
    ('gujarati', 'gu'),
    ('glv', 'gv'),
    ('gv', 'gv'),
    ('manx', 'gv'),
    ('ha', 'ha'),
    ('hau', 'ha'),
    ('hausa', 'ha'),
    ('he', 'he'),
    ('heb', 'he'),
    ('hebrew', 'he'),
    ('hi', 'hi'),
    ('hin', 'hi'),
    ('hindi', 'hi'),
    ('hiri motu', 'ho'),
    ('hmo', 'ho'),
    ('ho', 'ho'),
    ('croatian', 'hr'),
    ('hr', 'hr'),
    ('hrv', 'hr'),
    ('haitian', 'ht'),
    ('hat', 'ht'),
    ('ht', 'ht'),
    ('hu', 'hu'),
    ('hun', 'hu'),
    ('hungarian', 'hu'),
    ('arm', 'hy'),
    ('armenian', 'hy'),
    ('hy', 'hy'),
    ('hye', 'hy'),
    ('her', 'hz'),
    ('herero', 'hz'),
    ('hz', 'hz'),
    ('ia', 'ia'),
    ('ina', 'ia'),
    ('interlingua', 'ia'),
    ('id', 'id'),
    ('ind', 'id'),
    ('indonesian', 'id'),
    ('ie', 'ie'),
    ('ile', 'ie'),
    ('interlingue', 'ie'),
    ('ibo', 'ig'),
    ('ig', 'ig'),
    ('igbo', 'ig'),
    ('ii', 'ii'),
    ('iii', 'ii'),
    ('sichuan yi', 'ii'),
    ('ik', 'ik'),
    ('inupiaq', 'ik'),
    ('ipk', 'ik'),
    ('ido', 'io'),
    ('io', 'io'),
    ('ice', 'is'),
    ('icelandic', 'is'),
    ('is', 'is'),
    ('isl', 'is'),
    ('it', 'it'),
    ('ita', 'it'),
    ('italian', 'it'),
    ('iku', 'iu'),
    ('inuktitut', 'iu'),
    ('iu', 'iu'),
    ('ja', 'ja'),
    ('japanese', 'ja'),
    ('jpn', 'ja'),
    ('jav', 'jv'),
    ('javanese', 'jv'),
    ('jv', 'jv'),
    ('geo', 'ka'),
    ('georgian', 'ka'),
    ('ka', 'ka'),
    ('kat', 'ka'),
    ('kg', 'kg'),
    ('kon', 'kg'),
    ('kongo', 'kg'),
    ('ki', 'ki'),
    ('kik', 'ki'),
    ('kikuyu', 'ki'),
    ('kj', 'kj'),
    ('kua', 'kj'),
    ('kuanyama', 'kj'),
    ('kaz', 'kk'),
    ('kazakh', 'kk'),
    ('kk', 'kk'),
    ('kal', 'kl'),
    ('kalaallisut', 'kl'),
    ('kl', 'kl'),
    ('khm', 'km'),
    ('khmer', 'km'),
    ('km', 'km'),
    ('kan', 'kn'),
    ('kannada', 'kn'),
    ('kn', 'kn'),
    ('ko', 'ko'),
    ('kor', 'ko'),
    ('korean', 'ko'),
    ('kanuri', 'kr'),
    ('kau', 'kr'),
    ('kr', 'kr'),
    ('kas', 'ks'),
    ('kashmiri', 'ks'),
    ('ks', 'ks'),
    ('ku', 'ku'),
    ('kur', 'ku'),
    ('kurdish', 'ku'),
    ('kom', 'kv'),
    ('komi', 'kv'),
    ('kv', 'kv'),
    ('cor', 'kw'),
    ('cornish', 'kw'),
    ('kw', 'kw'),
    ('kir', 'ky'),
    ('kirghiz', 'ky'),
    ('ky', 'ky'),
    ('la', 'la'),
    ('lat', 'la'),
    ('latin', 'la'),
    ('lb', 'lb'),
    ('ltz', 'lb'),
    ('luxembourgish', 'lb'),
    ('ganda', 'lg'),
    ('lg', 'lg'),
    ('lug', 'lg'),
    ('li', 'li'),
    ('lim', 'li'),
    ('limburgan', 'li'),
    ('lin', 'ln'),
    ('lingala', 'ln'),
    ('ln', 'ln'),
    ('lao', 'lo'),
    ('lo', 'lo'),
    ('lit', 'lt'),
    ('lithuanian', 'lt'),
    ('lt', 'lt'),
    ('lu', 'lu'),
    ('lub', 'lu'),
    ('luba-katanga', 'lu'),
    ('latvian', 'lv'),
    ('lav', 'lv'),
    ('lv', 'lv'),
    ('malagasy', 'mg'),
    ('mg', 'mg'),
    ('mlg', 'mg'),
    ('mah', 'mh'),
    ('marshallese', 'mh'),
    ('mh', 'mh'),
    ('mao', 'mi'),
    ('maori', 'mi'),
    ('mi', 'mi'),
    ('mri', 'mi'),
    ('mac', 'mk'),
    ('macedonian', 'mk'),
    ('mk', 'mk'),
    ('mkd', 'mk'),
    ('mal', 'ml'),
    ('malayalam', 'ml'),
    ('ml', 'ml'),
    ('mn', 'mn'),
    ('mon', 'mn'),
    ('mongolian', 'mn'),
    ('mar', 'mr'),
    ('marathi', 'mr'),
    ('mr', 'mr'),
    ('malay', 'ms'),
    ('may', 'ms'),
    ('ms', 'ms'),
    ('msa', 'ms'),
    ('maltese', 'mt'),
    ('mlt', 'mt'),
    ('mt', 'mt'),
    ('bur', 'my'),
    ('burmese', 'my'),
    ('my', 'my'),
    ('mya', 'my'),
    ('na', 'na'),
    ('nau', 'na'),
    ('nauru', 'na'),
    ('nb', 'nb'),
    ('nob', 'nb'),
    ('norwegian bokmål', 'nb'),
    ('nd', 'nd'),
    ('nde', 'nd'),
    ('north ndebele', 'nd'),
    ('ne', 'ne'),
    ('nep', 'ne'),
    ('nepali', 'ne'),
    ('ndo', 'ng'),
    ('ndonga', 'ng'),
    ('ng', 'ng'),
    ('dut', 'nl'),
    ('dutch', 'nl'),
    ('nl', 'nl'),
    ('nld', 'nl'),
    ('nn', 'nn'),
    ('nno', 'nn'),
    ('norwegian nynorsk', 'nn'),
    ('no', 'no'),
    ('nor', 'no'),
    ('norwegian', 'no'),
    ('nbl', 'nr'),
    ('nr', 'nr'),
    ('south ndebele', 'nr'),
    ('nav', 'nv'),
    ('navajo', 'nv'),
    ('nv', 'nv'),
    ('chichewa', 'ny'),
    ('ny', 'ny'),
    ('nya', 'ny'),
    ('oc', 'oc'),
    ('occitan', 'oc'),
    ('oci', 'oc'),
    ('oj', 'oj'),
    ('oji', 'oj'),
    ('ojibwa', 'oj'),
    ('om', 'om'),
    ('orm', 'om'),
    ('oromo', 'om'),
    ('or', 'or'),
    ('ori', 'or'),
    ('oriya', 'or'),
    ('os', 'os'),
    ('oss', 'os'),
    ('ossetian', 'os'),
    ('pa', 'pa'),
    ('pan', 'pa'),
    ('panjabi', 'pa'),
    ('pali', 'pi'),
    ('pi', 'pi'),
    ('pli', 'pi'),
    ('pl', 'pl'),
    ('pol', 'pl'),
    ('polish', 'pl'),
    ('ps', 'ps'),
    ('pus', 'ps'),
    ('pushto', 'ps'),
    ('por', 'pt'),
    ('portuguese', 'pt'),
    ('pt', 'pt'),
    ('qu', 'qu'),
    ('que', 'qu'),
    ('quechua', 'qu'),
    ('rm', 'rm'),
    ('roh', 'rm'),
    ('romansh', 'rm'),
    ('rn', 'rn'),
    ('run', 'rn'),
    ('rundi', 'rn'),
    ('ro', 'ro'),
    ('romanian', 'ro'),
    ('ron', 'ro'),
    ('rum', 'ro'),
    ('ru', 'ru'),
    ('rus', 'ru'),
    ('russian', 'ru'),
    ('kin', 'rw'),
    ('kinyarwanda', 'rw'),
    ('rw', 'rw'),
    ('sa', 'sa'),
    ('san', 'sa'),
    ('sanskrit', 'sa'),
    ('sardinian', 'sc'),
    ('sc', 'sc'),
    ('srd', 'sc'),
    ('sd', 'sd'),
    ('sindhi', 'sd'),
    ('snd', 'sd'),
    ('northern sami', 'se'),
    ('se', 'se'),
    ('sme', 'se'),
    ('sag', 'sg'),
    ('sango', 'sg'),
    ('sg', 'sg'),
    ('hbs', 'sh'),
    ('serbo-croatian', 'sh'),
    ('sh', 'sh'),
    ('si', 'si'),
    ('sin', 'si'),
    ('sinhala', 'si'),
    ('sk', 'sk'),
    ('slk', 'sk'),
    ('slo', 'sk'),
    ('slovak', 'sk'),
    ('sl', 'sl'),
    ('slovenian', 'sl'),
    ('slv', 'sl'),
    ('samoan', 'sm'),
    ('sm', 'sm'),
    ('smo', 'sm'),
    ('shona', 'sn'),
    ('sn', 'sn'),
    ('sna', 'sn'),
    ('so', 'so'),
    ('som', 'so'),
    ('somali', 'so'),
    ('alb', 'sq'),
    ('albanian', 'sq'),
    ('sq', 'sq'),
    ('sqi', 'sq'),
    ('serbian', 'sr'),
    ('sr', 'sr'),
    ('srp', 'sr'),
    ('ss', 'ss'),
    ('ssw', 'ss'),
    ('swati', 'ss'),
    ('sot', 'st'),
    ('southern sotho', 'st'),
    ('st', 'st'),
    ('su', 'su'),
    ('sun', 'su'),
    ('sundanese', 'su'),
    ('sv', 'sv'),
    ('swe', 'sv'),
    ('swedish', 'sv'),
    ('sw', 'sw'),
    ('swa', 'sw'),
    ('swahili', 'sw'),
    ('ta', 'ta'),
    ('tam', 'ta'),
    ('tamil', 'ta'),
    ('te', 'te'),
    ('tel', 'te'),
    ('telugu', 'te'),
    ('tajik', 'tg'),
    ('tg', 'tg'),
    ('tgk', 'tg'),
    ('th', 'th'),
    ('tha', 'th'),
    ('thai', 'th'),
    ('ti', 'ti'),
    ('tigrinya', 'ti'),
    ('tir', 'ti'),
    ('tk', 'tk'),
    ('tuk', 'tk'),
    ('turkmen', 'tk'),
    ('tagalog', 'tl'),
    ('tgl', 'tl'),
    ('tl', 'tl'),
    ('tn', 'tn'),
    ('tsn', 'tn'),
    ('tswana', 'tn'),
    ('to', 'to'),
    ('ton', 'to'),
    ('tonga', 'to'),
    ('tr', 'tr'),
    ('tur', 'tr'),
    ('turkish', 'tr'),
    ('ts', 'ts'),
    ('tso', 'ts'),
    ('tsonga', 'ts'),
    ('tat', 'tt'),
    ('tatar', 'tt'),
    ('tt', 'tt'),
    ('tw', 'tw'),
    ('twi', 'tw'),
    ('tah', 'ty'),
    ('tahitian', 'ty'),
    ('ty', 'ty'),
    ('ug', 'ug'),
    ('uig', 'ug'),
    ('uighur', 'ug'),
    ('uk', 'uk'),
    ('ukr', 'uk'),
    ('ukrainian', 'uk'),
    ('ur', 'ur'),
    ('urd', 'ur'),
    ('urdu', 'ur'),
    ('uz', 'uz'),
    ('uzb', 'uz'),
    ('uzbek', 'uz'),
    ('ve', 've'),
    ('ven', 've'),
    ('venda', 've'),
    ('vi', 'vi'),
    ('vie', 'vi'),
    ('vietnamese', 'vi'),
    ('vo', 'vo'),
    ('vol', 'vo'),
    ('volapük', 'vo'),
    ('wa', 'wa'),
    ('walloon', 'wa'),
    ('wln', 'wa'),
    ('wo', 'wo'),
    ('wol', 'wo'),
    ('wolof', 'wo'),
    ('xh', 'xh'),
    ('xho', 'xh'),
    ('xhosa', 'xh'),
    ('yi', 'yi'),
    ('yid', 'yi'),
    ('yiddish', 'yi'),
    ('yo', 'yo'),
    ('yor', 'yo'),
    ('yoruba', 'yo'),
    ('za', 'za'),
    ('zha', 'za'),
    ('zhuang', 'za'),
    ('chi', 'zh'),
    ('chinese', 'zh'),
    ('zh', 'zh'),
    ('zho', 'zh'),
    ('zu', 'zu'),
    ('zul', 'zu'),
    ('zulu', 'zu');
"""

_DOWNGRADE = """
DROP TABLE public.language_forms;
DROP TABLE public.languages;
"""


def upgrade() -> None:
    op.execute(_UPGRADE)


def downgrade() -> None:
    op.execute(_DOWNGRADE)
