"""place_name_forms : 2e fournee de noms d'universites (depuis suggestions)

Meme decouverte que la 1re marche (n-grammes autour de universite/university,
dedup suffixe), mais sur les adresses SANS pays a suggestion UNIQUE et coherente
(cardinality(suggested_countries)=1) au lieu des adresses a pays. La suggestion
joue le role du pays. Formes inedites uniquement (hors deja seedees).

Revision ID: b9d4e7a2f5c8
Revises: a4c7e2f9b6d1
Create Date: 2026-06-12 10:00:00.000000
"""

from collections.abc import Sequence

from alembic import op

revision: str = "b9d4e7a2f5c8"
down_revision: str | Sequence[str] | None = "a4c7e2f9b6d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        INSERT INTO place_name_forms (iso_code, form_normalized, kind) VALUES
            ('us', 'university of washington seattle', 'institution'),
            ('ca', 'university of british columbia', 'institution'),
            ('fr', 'university of lille chu', 'institution'),
            ('br', 'university of sao paulo', 'institution'),
            ('us', 'university of texas health', 'institution'),
            ('us', 'university of north carolina', 'institution'),
            ('us', 'university of california davis', 'institution'),
            ('us', 'university of california berkeley', 'institution'),
            ('pt', 'university of tras os', 'institution'),
            ('us', 'university of texas southwestern', 'institution'),
            ('de', 'university of duisburg essen', 'institution'),
            ('au', 'university of queensland brisbane', 'institution'),
            ('it', 'university of naples federico', 'institution'),
            ('us', 'university of hawai i', 'institution'),
            ('fr', 'department lille university hospital', 'institution'),
            ('us', 'university of maryland college', 'institution'),
            ('us', 'university of colorado boulder', 'institution'),
            ('gb', 'university of east anglia', 'institution'),
            ('nl', 'university of groningen university', 'institution'),
            ('us', 'university of new york', 'institution'),
            ('us', 'university of south florida', 'institution'),
            ('us', 'university of south carolina', 'institution'),
            ('ch', 'inselspital bern university hospital', 'institution'),
            ('us', 'university of wisconsin school', 'institution'),
            ('us', 'university of utah salt', 'institution'),
            ('us', 'university of minnesota minneapolis', 'institution'),
            ('cn', 'university of chinese academy', 'institution'),
            ('fi', 'university of eastern finland', 'institution'),
            ('cl', 'university of chile santiago', 'institution'),
            ('br', 'university of rio grande', 'institution'),
            ('us', 'university of arizona tucson', 'institution'),
            ('dk', 'university of southern denmark', 'institution'),
            ('hr', 'university of zagreb school', 'institution'),
            ('us', 'university of colorado school', 'institution'),
            ('br', 'university of campinas unicamp', 'institution'),
            ('fr', 'university of lille 59000', 'institution'),
            ('us', 'university of michigan medical', 'institution'),
            ('se', 'university of gothenburg molndal', 'institution'),
            ('it', 'university of milano bicocca', 'institution'),
            ('fr', 'grenoble alpes university hospital', 'institution'),
            ('gb', 'university of edinburgh united', 'institution'),
            ('za', 'university of the witwatersrand', 'institution'),
            ('it', 'university of modena and', 'institution'),
            ('au', 'university of melbourne parkville', 'institution'),
            ('fr', 'pitie salpetriere university hospital', 'institution'),
            ('us', 'university of california irvine', 'institution'),
            ('fr', 'university of clermont auvergne', 'institution'),
            ('es', 'd hebron university hospital', 'institution'),
            ('rs', 'university of novi sad', 'institution'),
            ('au', 'university of tasmania hobart', 'institution'),
            ('fr', 'digestive surgery university hospital', 'institution'),
            ('fr', 'care unit university hospital', 'institution'),
            ('cm', 'university of yaounde i', 'institution'),
            ('us', 'university of virginia charlottesville', 'institution'),
            ('es', 'university of the basque', 'institution'),
            ('fr', 'pathology department university hospital', 'institution'),
            ('fr', 'university of picardie jules', 'institution'),
            ('fr', 'pediatric surgery university hospital', 'institution'),
            ('us', 'university of georgia athens', 'institution'),
            ('it', 'university of campania luigi', 'institution'),
            ('ca', 'university of saskatchewan saskatoon', 'institution'),
            ('it', 'university of l aquila', 'institution'),
            ('fr', 'university of lille nord', 'institution'),
            ('fr', 'enfants malades university hospital', 'institution'),
            ('de', 'university of freiburg faculty', 'institution'),
            ('ie', 'university of ireland galway', 'institution'),
            ('ch', 'university of bern switzerland', 'institution'),
            ('fr', 'university of lille villeneuve', 'institution'),
            ('au', 'university of technology brisbane', 'institution'),
            ('us', 'university of oklahoma norman', 'institution'),
            ('ph', 'university of the philippines', 'institution'),
            ('us', 'university of maryland school', 'institution'),
            ('de', 'and allergy university hospital', 'institution'),
            ('gb', 'and norwich university hospital', 'institution'),
            ('is', 'university of iceland reykjavik', 'institution'),
            ('fr', 'la timone university hospital', 'institution'),
            ('fr', 'university of reims champagne', 'institution'),
            ('us', 'university of texas medical', 'institution'),
            ('fr', 'university of lille umr', 'institution'),
            ('cn', 'university of geosciences wuhan', 'institution'),
            ('sk', 'university of technology 81237', 'institution'),
            ('jp', 'university of tokyo 4', 'institution'),
            ('fr', 'university of paris sud', 'institution'),
            ('us', 'university of connecticut storrs', 'institution'),
            ('us', 'university of oregon eugene', 'institution'),
            ('pl', 'university of warmia and', 'institution'),
            ('jp', 'university of marine science', 'institution'),
            ('bj', 'university of abomey calavi', 'institution'),
            ('us', 'university of kansas medical', 'institution'),
            ('pt', 'university of minho braga', 'institution'),
            ('fi', 'university of helsinki finland', 'institution'),
            ('gb', 'university of warwick coventry', 'institution'),
            ('be', 'university of mons umons', 'institution'),
            ('cn', 'university of aeronautics and', 'institution'),
            ('fr', 'dermatology department university hospital', 'institution'),
            ('gb', 'university of surrey guildford', 'institution'),
            ('de', 'university of cologne medical', 'institution'),
            ('us', 'university of central florida', 'institution'),
            ('us', 'university of massachusetts medical', 'institution'),
            ('de', 'adolescent medicine university hospital', 'institution'),
            ('ca', 'university of manitoba winnipeg', 'institution'),
            ('fr', 'university of picardie amiens', 'institution'),
            ('au', 'university of technology sydney', 'institution'),
            ('ch', 'of psychiatry university hospital', 'institution'),
            ('es', 'university of barcelona idibaps', 'institution'),
            ('us', 'university of rochester school', 'institution'),
            ('ca', 'university of toronto', 'institution'),
            ('fr', 'universite de paris', 'institution'),
            ('fr', 'universite paris cite', 'institution'),
            ('gb', 'university of cambridge', 'institution'),
            ('nl', 'university of amsterdam', 'institution'),
            ('gb', 'university of edinburgh', 'institution'),
            ('fr', 'universite de lorraine', 'institution'),
            ('fr', 'universite d auvergne', 'institution'),
            ('fr', 'aix marseille university', 'institution'),
            ('fr', 'universite paris descartes', 'institution'),
            ('fr', 'universite grenoble alpes', 'institution'),
            ('ch', 'university of bern', 'institution'),
            ('fr', 'universite blaise pascal', 'institution'),
            ('se', 'university of gothenburg', 'institution'),
            ('ca', 'university of british', 'institution'),
            ('gb', 'university of manchester', 'institution'),
            ('ch', 'university of zurich', 'institution'),
            ('de', 'university of cologne', 'institution'),
            ('fr', 'universite de lyon', 'institution'),
            ('nl', 'university of groningen', 'institution'),
            ('cn', 'jiao tong university', 'institution'),
            ('fr', 'universite claude bernard', 'institution'),
            ('gr', 'university of athens', 'institution'),
            ('fr', 'universite paris est', 'institution'),
            ('us', 'university of maryland', 'institution'),
            ('fr', 'universite de nantes', 'institution'),
            ('fr', 'universite du littoral', 'institution'),
            ('dk', 'university of copenhagen', 'institution'),
            ('il', 'tel aviv university', 'institution'),
            ('fr', 'universite lille nord', 'institution'),
            ('fr', 'universite de picardie', 'institution'),
            ('br', 'university of sao', 'institution'),
            ('fr', 'universite de strasbourg', 'institution'),
            ('pt', 'university of coimbra', 'institution'),
            ('fr', 'universite de bourgogne', 'institution'),
            ('us', 'university of colorado', 'institution'),
            ('gb', 'university of glasgow', 'institution'),
            ('jp', 'university of tokyo', 'institution'),
            ('be', 'university of antwerp', 'institution'),
            ('no', 'oslo university hospital', 'institution'),
            ('fr', 'universite paris diderot', 'institution'),
            ('gb', 'university of southampton', 'institution'),
            ('sg', 'university of singapore', 'institution'),
            ('fr', 'universite de poitiers', 'institution'),
            ('it', 'university of milan', 'institution'),
            ('gb', 'university of bristol', 'institution'),
            ('us', 'university of north', 'institution'),
            ('no', 'university of oslo', 'institution'),
            ('it', 'university of naples', 'institution'),
            ('sg', 'nanyang technological university', 'institution'),
            ('fr', 'psl research university', 'institution'),
            ('fr', 'universite de toulouse', 'institution'),
            ('be', 'university of liege', 'institution'),
            ('de', 'university of freiburg', 'institution'),
            ('fr', 'universite d artois', 'institution'),
            ('hr', 'university of zagreb', 'institution'),
            ('fr', 'paris descartes university', 'institution'),
            ('fr', 'universite de bordeaux', 'institution'),
            ('si', 'university of ljubljana', 'institution'),
            ('pt', 'university of lisbon', 'institution'),
            ('fr', 'lille catholic university', 'institution'),
            ('be', 'university of mons', 'institution'),
            ('fr', 'universite paris sud', 'institution'),
            ('pt', 'university of porto', 'institution'),
            ('ch', 'university of basel', 'institution'),
            ('it', 'university of brescia', 'institution'),
            ('it', 'university of florence', 'institution'),
            ('fr', 'universite de rennes', 'institution'),
            ('pl', 'university of warsaw', 'institution'),
            ('us', 'university of illinois', 'institution'),
            ('at', 'university of innsbruck', 'institution'),
            ('it', 'university of bologna', 'institution'),
            ('us', 'arizona state university', 'institution'),
            ('us', 'university of utah', 'institution'),
            ('us', 'university of iowa', 'institution'),
            ('de', 'university of lubeck', 'institution'),
            ('us', 'university of arizona', 'institution'),
            ('it', 'university of padua', 'institution'),
            ('fr', 'amiens university hospital', 'institution'),
            ('fr', 'toulouse university hospital', 'institution'),
            ('gb', 'university of birmingham', 'institution'),
            ('de', 'university of bonn', 'institution'),
            ('au', 'western sydney university', 'institution'),
            ('pt', 'university of tras', 'institution'),
            ('fr', 'university of paris', 'institution'),
            ('ca', 'university of calgary', 'institution'),
            ('gb', 'university of exeter', 'institution'),
            ('de', 'university of duisburg', 'institution'),
            ('cl', 'university of chile', 'institution'),
            ('tw', 'national taiwan university', 'institution'),
            ('ca', 'university of waterloo', 'institution'),
            ('sa', 'king saud university', 'institution'),
            ('it', 'university of genoa', 'institution'),
            ('nz', 'university of auckland', 'institution'),
            ('fr', 'universite de versailles', 'institution'),
            ('us', 'michigan state university', 'institution'),
            ('gr', 'university of crete', 'institution'),
            ('rs', 'university of belgrade', 'institution'),
            ('ru', 'moscow state university', 'institution'),
            ('us', 'california state university', 'institution'),
            ('il', 'university of jerusalem', 'institution'),
            ('gb', 'university of liverpool', 'institution'),
            ('fr', 'rouen university hospital', 'institution'),
            ('fr', 'universite de caen', 'institution'),
            ('de', 'university of heidelberg', 'institution'),
            ('gb', 'university of east', 'institution'),
            ('fr', 'universite de bretagne', 'institution'),
            ('fr', 'paris saclay university', 'institution'),
            ('fr', 'universite paris nanterre', 'institution'),
            ('de', 'justus liebig university', 'institution'),
            ('fr', 'universite de montpellier', 'institution'),
            ('fr', 'universite paris france', 'institution'),
            ('pl', 'university of lodz', 'institution'),
            ('ch', 'lausanne university hospital', 'institution'),
            ('fr', 'universite de franche', 'institution'),
            ('fr', 'universite de limoges', 'institution'),
            ('ca', 'universite de sherbrooke', 'institution'),
            ('us', 'university of hawai', 'institution'),
            ('it', 'university of messina', 'institution'),
            ('de', 'martin luther university', 'institution'),
            ('ca', 'institute mcgill university', 'institution'),
            ('us', 'pennsylvania state university', 'institution'),
            ('fi', 'helsinki university hospital', 'institution'),
            ('de', 'university of bayreuth', 'institution'),
            ('au', 'university of tasmania', 'institution'),
            ('us', 'university of massachusetts', 'institution'),
            ('de', 'university of munster', 'institution'),
            ('ru', 'national research university', 'institution'),
            ('fr', 'universite d evry', 'institution'),
            ('fr', 'universite toulouse iii', 'institution'),
            ('fr', 'universite d angers', 'institution'),
            ('fr', 'universite savoie mont', 'institution'),
            ('gb', 'university of leicester', 'institution'),
            ('fr', 'clermont auvergne university', 'institution'),
            ('de', 'von guericke university', 'institution'),
            ('us', 'university of virginia', 'institution'),
            ('at', 'university of graz', 'institution'),
            ('ca', 'university of montreal', 'institution'),
            ('fr', 'universite de rouen', 'institution'),
            ('fr', 'university of picardie', 'institution'),
            ('fr', 'universite de tours', 'institution'),
            ('cn', 'capital medical university', 'institution'),
            ('kr', 'seoul national university', 'institution'),
            ('se', 'sahlgrenska university hospital', 'institution'),
            ('it', 'university of milano', 'institution'),
            ('au', 'school monash university', 'institution'),
            ('us', 'university of miami', 'institution'),
            ('cn', 'university of chinese', 'institution'),
            ('fr', 'blaise pascal university', 'institution'),
            ('fr', 'universite lille 3', 'institution'),
            ('be', 'chemistry ghent university', 'institution'),
            ('ee', 'university of tartu', 'institution'),
            ('ie', 'university of ireland', 'institution'),
            ('nl', 'erasmus mc university', 'institution'),
            ('it', 'university of palermo', 'institution'),
            ('us', 'university of florida', 'institution'),
            ('de', 'university of wurzburg', 'institution'),
            ('gb', 'university of york', 'institution'),
            ('fr', 'universite d orleans', 'institution'),
            ('fr', 'university of tours', 'institution'),
            ('is', 'university of iceland', 'institution'),
            ('za', 'sciences stellenbosch university', 'institution'),
            ('se', 'skane university hospital', 'institution'),
            ('gr', 'university of thessaly', 'institution'),
            ('fr', 'paris sud university', 'institution'),
            ('ca', 'psychiatry mcgill university', 'institution'),
            ('za', 'university of johannesburg', 'institution'),
            ('fr', 'paris diderot university', 'institution'),
            ('fr', 'nancy university hospital', 'institution'),
            ('us', 'university of tennessee', 'institution'),
            ('fr', 'lyon 1 university', 'institution'),
            ('fr', 'universite lyon 1', 'institution'),
            ('au', 'university of adelaide', 'institution'),
            ('pl', 'university of gdansk', 'institution'),
            ('cn', 'china normal university', 'institution'),
            ('ca', 'simon fraser university', 'institution'),
            ('es', 'university of granada', 'institution'),
            ('fr', 'reims university hospital', 'institution'),
            ('fr', 'universite polytechnique hauts', 'institution'),
            ('fr', 'universite lille chu', 'institution'),
            ('pt', 'university of minho', 'institution'),
            ('nl', 'neuroscience maastricht university', 'institution'),
            ('gb', 'university of dundee', 'institution'),
            ('it', 'university of turin', 'institution'),
            ('es', 'university of navarra', 'institution'),
            ('de', 'heinrich heine university', 'institution'),
            ('ma', 'universite hassan ii', 'institution'),
            ('gb', 'university of warwick', 'institution'),
            ('de', 'university of leipzig', 'institution'),
            ('fr', 'universite ap hp', 'institution'),
            ('ch', 'university of neuchatel', 'institution'),
            ('de', 'university of kiel', 'institution'),
            ('dz', 'universite de bejaia', 'institution'),
            ('fr', 'university of strasbourg', 'institution'),
            ('de', 'university of bremen', 'institution'),
            ('au', 'australian national university', 'institution'),
            ('gb', 'university of aberdeen', 'institution'),
            ('ca', 'university of saskatchewan', 'institution'),
            ('de', 'university of tubingen', 'institution'),
            ('ro', 'babes bolyai university', 'institution'),
            ('ge', 'tbilisi state university', 'institution'),
            ('fr', 'universite toulouse jean', 'institution'),
            ('de', 'university of hamburg', 'institution'),
            ('us', 'university of oklahoma', 'institution'),
            ('fi', 'university of oulu', 'institution'),
            ('no', 'university of bergen', 'institution'),
            ('de', 'johannes gutenberg university', 'institution'),
            ('fr', 'university of rouen', 'institution'),
            ('it', 'university of pisa', 'institution'),
            ('ca', 'mental health university', 'institution'),
            ('it', 'university of modena', 'institution'),
            ('fr', 'universite de technologie', 'institution'),
            ('us', 'george washington university', 'institution'),
            ('mk', 'and methodius university', 'institution'),
            ('fr', 'rennes university hospital', 'institution'),
            ('fr', 'universite bourgogne franche', 'institution'),
            ('us', 'medicine northwestern university', 'institution'),
            ('cz', 'science charles university', 'institution'),
            ('th', 'chiang mai university', 'institution'),
            ('it', 'university of verona', 'institution'),
            ('dk', 'odense university hospital', 'institution'),
            ('it', 'university of cagliari', 'institution'),
            ('fr', 'universite francois rabelais', 'institution'),
            ('de', 'university of ulm', 'institution'),
            ('fr', 'universite paul sabatier', 'institution'),
            ('ro', 'university of bucharest', 'institution'),
            ('fr', 'universite de pau', 'institution'),
            ('fr', 'university of clermont', 'institution'),
            ('fr', 'universite sorbonne nouvelle', 'institution'),
            ('cn', 'university of geosciences', 'institution'),
            ('us', 'of brown university', 'institution'),
            ('cn', 'beijing jiaotong university', 'institution'),
            ('tw', 'taipei medical university', 'institution'),
            ('ru', 'novosibirsk state university', 'institution'),
            ('hu', 'university of pecs', 'institution'),
            ('us', 'state polytechnic university', 'institution'),
            ('fr', 'universite paris 13', 'institution'),
            ('it', 'university of padova', 'institution'),
            ('it', 'university of catania', 'institution'),
            ('fr', 'strasbourg university hospital', 'institution'),
            ('gb', 'university of kent', 'institution'),
            ('gb', 'university of bath', 'institution'),
            ('lb', 'universite saint joseph', 'institution'),
            ('us', 'louisiana state university', 'institution'),
            ('fr', 'angers university hospital', 'institution'),
            ('rs', 'university of novi', 'institution'),
            ('fr', 'university of lorraine', 'institution'),
            ('cn', 'beijing normal university', 'institution'),
            ('fr', 'university of orleans', 'institution'),
            ('fr', 'bordeaux university hospital', 'institution'),
            ('de', 'university of oldenburg', 'institution'),
            ('fr', 'university of nantes', 'institution'),
            ('us', 'university of kansas', 'institution'),
            ('fr', 'universite sorbonne paris', 'institution'),
            ('fr', 'university of rennes', 'institution'),
            ('us', 'university of nebraska', 'institution'),
            ('br', 'paulo state university', 'institution'),
            ('fr', 'university of bordeaux', 'institution'),
            ('fr', 'nice university hospital', 'institution'),
            ('us', 'sciences purdue university', 'institution'),
            ('fi', 'tampere university hospital', 'institution'),
            ('it', 'san raffaele university', 'institution'),
            ('fr', 'universite de perpignan', 'institution'),
            ('us', 'western reserve university', 'institution'),
            ('ma', 'chouaib doukkali university', 'institution'),
            ('us', 'diego state university', 'institution'),
            ('be', 'biology ghent university', 'institution'),
            ('gb', 'university of surrey', 'institution'),
            ('eg', 'ain shams university', 'institution'),
            ('it', 'university of campania', 'institution'),
            ('de', 'rwth aachen university', 'institution'),
            ('fr', 'montpellier university hospital', 'institution'),
            ('it', 'university of torino', 'institution'),
            ('cn', 'university of macau', 'institution'),
            ('fr', 'universite de clermont', 'institution'),
            ('ca', 'university of quebec', 'institution'),
            ('za', 'nelson mandela university', 'institution'),
            ('us', 'colorado state university', 'institution'),
            ('vn', 'vietnam national university', 'institution'),
            ('cg', 'universite marien ngouabi', 'institution'),
            ('gb', 'university of sussex', 'institution'),
            ('fr', 'universite versailles saint', 'institution'),
            ('dk', 'university of denmark', 'institution'),
            ('fi', 'university of turku', 'institution'),
            ('fr', 'universite le havre', 'institution'),
            ('us', 'university of houston', 'institution'),
            ('sn', 'universite gaston berger', 'institution'),
            ('fr', 'caen university hospital', 'institution'),
            ('it', 'university of trieste', 'institution'),
            ('it', 'university of salerno', 'institution'),
            ('fr', 'en yvelines university', 'institution'),
            ('nl', 'sciences utrecht university', 'institution'),
            ('hu', 'medicine semmelweis university', 'institution'),
            ('fr', 'universite lyon 2', 'institution'),
            ('br', 'university of parana', 'institution'),
            ('gb', 'university of portsmouth', 'institution'),
            ('cn', 'university of aeronautics', 'institution'),
            ('fr', 'university of reims', 'institution'),
            ('de', 'ludwig maximilians university', 'institution'),
            ('us', 'kansas state university', 'institution'),
            ('nz', 'university of canterbury', 'institution'),
            ('hu', 'university of debrecen', 'institution'),
            ('it', 'university of l', 'institution'),
            ('fr', 'universite lille 1', 'institution'),
            ('ma', 'vi polytechnic university', 'institution'),
            ('us', 'university of oregon', 'institution'),
            ('sa', 'science taif university', 'institution'),
            ('fr', 'dijon university hospital', 'institution'),
            ('be', 'sciences ghent university', 'institution'),
            ('dz', 'universite d oran', 'institution'),
            ('tn', 'university of tunis', 'institution'),
            ('dz', 'universite mouloud mammeri', 'institution'),
            ('ro', 'university of iasi', 'institution'),
            ('ma', 'universite cadi ayyad', 'institution'),
            ('fr', 'universite de toulon', 'institution'),
            ('ir', 'university of tehran', 'institution'),
            ('br', 'university of pernambuco', 'institution'),
            ('de', 'university of siegen', 'institution'),
            ('de', 'university of konstanz', 'institution'),
            ('mg', 'universite d antananarivo', 'institution'),
            ('ie', 'university of dublin', 'institution'),
            ('gb', 'university of reading', 'institution'),
            ('us', 'and science university', 'institution'),
            ('sa', 'king abdulaziz university', 'institution'),
            ('il', 'bar ilan university', 'institution'),
            ('es', 'university of zaragoza', 'institution'),
            ('ch', 'geneva university hospital', 'institution'),
            ('us', 'university of nevada', 'institution'),
            ('fr', 'universite littoral cote', 'institution'),
            ('it', 'university of parma', 'institution'),
            ('ch', 'universite de neuchatel', 'institution'),
            ('za', 'university of pretoria', 'institution'),
            ('sa', 'bin abdulaziz university', 'institution'),
            ('it', 'university of bari', 'institution'),
            ('jp', 'wakayama medical university', 'institution'),
            ('lb', 'saint joseph university', 'institution'),
            ('cz', 'university of ostrava', 'institution'),
            ('fr', 'universite paul valery', 'institution'),
            ('fr', 'paris nord university', 'institution'),
            ('pl', 'adam mickiewicz university', 'institution'),
            ('dk', 'aarhus university hospital', 'institution'),
            ('fr', 'universite lille iii', 'institution'),
            ('ca', 'university of manitoba', 'institution'),
            ('fr', 'lille france university', 'institution'),
            ('sn', 'universite cheikh anta', 'institution'),
            ('fr', 'cochin university hospital', 'institution'),
            ('us', 'medicine columbia university', 'institution'),
            ('tw', 'taiwan ocean university', 'institution'),
            ('se', 'sciences lund university', 'institution'),
            ('gb', 'medicine cardiff university', 'institution'),
            ('lb', 'lebanese american university', 'institution'),
            ('fr', 'universite marseille france', 'institution'),
            ('ca', 'neurosurgery mcgill university', 'institution'),
            ('es', 'university of valencia', 'institution'),
            ('pl', 'wroclaw medical university', 'institution'),
            ('tn', 'universite de sousse', 'institution'),
            ('es', 'university of malaga', 'institution'),
            ('cn', 'university of china', 'institution'),
            ('us', 'university of connecticut', 'institution'),
            ('cz', 'czech technical university', 'institution'),
            ('fr', 'lyon university hospital', 'institution'),
            ('cn', 'capital normal university', 'institution'),
            ('dz', 'university of biskra', 'institution'),
            ('be', 'universite de mons', 'institution'),
            ('pl', 'university of warmia', 'institution'),
            ('ma', 'universite ibn zohr', 'institution'),
            ('es', 'university of murcia', 'institution'),
            ('de', 'university of potsdam', 'institution'),
            ('jp', 'university of marine', 'institution'),
            ('bj', 'university of abomey', 'institution'),
            ('be', 'university of brussels', 'institution'),
            ('ca', 'university of guelph', 'institution'),
            ('us', 'oklahoma state university', 'institution'),
            ('fr', 'universite paris dauphine', 'institution'),
            ('ie', 'university of limerick', 'institution'),
            ('au', 'australian catholic university', 'institution'),
            ('cz', 'charles university hospital', 'institution'),
            ('us', 'university of alaska', 'institution'),
            ('gb', 'university of plymouth', 'institution'),
            ('us', 'university of cincinnati', 'institution'),
            ('cn', 'engineering hohai university', 'institution'),
            ('it', 'university of udine', 'institution'),
            ('fr', 'university of auvergne', 'institution'),
            ('tn', 'universite de carthage', 'institution'),
            ('fr', 'university of limoges', 'institution'),
            ('fr', 'grenoble alpes university', 'institution'),
            ('fr', 'care university hospital', 'institution'),
            ('us', 'old dominion university', 'institution'),
            ('cm', 'university of ngaoundere', 'institution'),
            ('ir', 'university of mashhad', 'institution'),
            ('ca', 'the mcgill university', 'institution'),
            ('no', 'university of norway', 'institution'),
            ('gr', 'university of thrace', 'institution'),
            ('de', 'heidelberg university hospital', 'institution'),
            ('es', 'university of santiago', 'institution'),
            ('om', 'sultan qaboos university', 'institution'),
            ('de', 'friedrich alexander university', 'institution'),
            ('pt', 'university of aveiro', 'institution'),
            ('ua', 'dnipro national university', 'institution'),
            ('de', 'university of erlangen', 'institution'),
            ('us', 'southern illinois university', 'institution'),
            ('fr', 'universite de nimes', 'institution'),
            ('fr', 'universite bordeaux montaigne', 'institution'),
            ('fr', 'universite picardie jules', 'institution'),
            ('us', 'health science university', 'institution'),
            ('fr', 'universite d avignon', 'institution'),
            ('ma', 'universite mohammed premier', 'institution'),
            ('de', 'university of gottingen', 'institution'),
            ('dz', 'universite badji mokhtar', 'institution'),
            ('il', 'university of haifa', 'institution'),
            ('nl', 'group wageningen university', 'institution'),
            ('th', 'hospital mahidol university', 'institution'),
            ('ca', 'centre mcgill university', 'institution'),
            ('fi', 'oulu university hospital', 'institution'),
            ('fr', 'de lille university', 'institution'),
            ('ca', 'university of victoria', 'institution'),
            ('cn', 'sciences zhejiang university', 'institution'),
            ('cn', 'university of electronic', 'institution'),
            ('es', 'university of seville', 'institution'),
            ('ru', 'tomsk state university', 'institution'),
            ('fr', 'universite aix marseille', 'institution'),
            ('it', 'university of perugia', 'institution'),
            ('it', 'university of insubria', 'institution'),
            ('fr', 'est creteil university', 'institution'),
            ('fr', 'universite lille', 'institution'),
            ('fr', 'universite grenoble', 'institution'),
            ('fr', 'universite blaise', 'institution'),
            ('nl', 'radboud university', 'institution'),
            ('fr', 'universite claude', 'institution'),
            ('fr', 'universite toulouse', 'institution'),
            ('us', 'duke university', 'institution'),
            ('fr', 'universite faculte', 'institution'),
            ('us', 'boston university', 'institution'),
            ('fr', 'universite lyon', 'institution'),
            ('lb', 'lebanese university', 'institution'),
            ('fr', 'universite sorbonne', 'institution'),
            ('gb', 'durham university', 'institution'),
            ('fr', 'universite pierre', 'institution'),
            ('us', 'emory university', 'institution'),
            ('sk', 'comenius university', 'institution'),
            ('fr', 'universite paul', 'institution'),
            ('za', 'rhodes university', 'institution'),
            ('nl', 'erasmus university', 'institution'),
            ('fr', 'universite savoie', 'institution'),
            ('de', 'ruhr university', 'institution'),
            ('gb', 'newcastle university', 'institution'),
            ('jp', 'tohoku university', 'institution'),
            ('jp', 'hokkaido university', 'institution'),
            ('fr', 'universite bourgogne', 'institution'),
            ('tr', 'hacettepe university', 'institution'),
            ('cn', 'peking university', 'institution'),
            ('us', 'rutgers university', 'institution'),
            ('ch', 'geneva university', 'institution'),
            ('fi', 'aalto university', 'institution'),
            ('jp', 'kyoto university', 'institution'),
            ('cn', 'guangxi university', 'institution'),
            ('ma', 'universite hassan', 'institution'),
            ('fr', 'universite versailles', 'institution'),
            ('fr', 'universite ap', 'institution'),
            ('de', 'goethe university', 'institution'),
            ('lt', 'vilnius university', 'institution'),
            ('cn', 'wuhan university', 'institution'),
            ('cn', 'nanjing university', 'institution'),
            ('be', 'hasselt university', 'institution'),
            ('fr', 'paris university', 'institution'),
            ('au', 'murdoch university', 'institution'),
            ('fr', 'universite francois', 'institution'),
            ('ca', 'dalhousie university', 'institution'),
            ('jp', 'gakuin university', 'institution'),
            ('us', 'hackensack university', 'institution'),
            ('kr', 'yonsei university', 'institution'),
            ('us', 'loyola university', 'institution'),
            ('ma', 'universite ibn', 'institution'),
            ('sa', 'qassim university', 'institution'),
            ('dk', 'aarhus university', 'institution'),
            ('jp', 'nagoya university', 'institution'),
            ('fr', 'universite nantes', 'institution'),
            ('us', 'baylor university', 'institution'),
            ('nz', 'massey university', 'institution'),
            ('jp', 'ehime university', 'institution'),
            ('tr', 'istanbul university', 'institution'),
            ('fr', 'universite marseille', 'institution'),
            ('de', 'saarland university', 'institution'),
            ('de', 'ulm university', 'institution'),
            ('fr', 'universite bordeaux', 'institution'),
            ('ca', 'laval university', 'institution'),
            ('fi', 'tampere university', 'institution'),
            ('gb', 'brunel university', 'institution'),
            ('cg', 'universite marien', 'institution'),
            ('gb', 'lancaster university', 'institution'),
            ('cn', 'tongji university', 'institution'),
            ('sn', 'universite gaston', 'institution'),
            ('cn', 'shenzhen university', 'institution'),
            ('eg', 'menoufia university', 'institution'),
            ('de', 'philipps university', 'institution'),
            ('cn', 'shanghai university', 'institution'),
            ('tr', 'ankara university', 'institution'),
            ('fr', 'montpellier university', 'institution'),
            ('fr', 'universite hopital', 'institution'),
            ('jp', 'osaka university', 'institution'),
            ('fi', 'helsinki university', 'institution'),
            ('nl', 'tilburg university', 'institution'),
            ('cn', 'xiamen university', 'institution'),
            ('dz', 'universite mouloud', 'institution'),
            ('ma', 'universite cadi', 'institution'),
            ('de', 'kiel university', 'institution'),
            ('cn', 'shandong university', 'institution'),
            ('kr', 'korea university', 'institution'),
            ('fr', 'universite littoral', 'institution'),
            ('jp', 'hiroshima university', 'institution'),
            ('cz', 'mendel university', 'institution'),
            ('us', 'rice university', 'institution'),
            ('in', 'pondicherry university', 'institution'),
            ('cn', 'sichuan university', 'institution'),
            ('sa', 'faisal university', 'institution'),
            ('fr', 'psl university', 'institution'),
            ('jp', 'kumamoto university', 'institution'),
            ('gb', 'manchester university', 'institution'),
            ('nl', 'pulmonology university', 'institution'),
            ('de', 'heidelberg university', 'institution'),
            ('sn', 'universite cheikh', 'institution'),
            ('se', 'linkoping university', 'institution'),
            ('tr', 'cukurova university', 'institution'),
            ('ru', 'federal university', 'institution'),
            ('fr', 'toulouse university', 'institution'),
            ('au', 'deakin university', 'institution'),
            ('fr', 'universite montpellier', 'institution'),
            ('cn', 'jinan university', 'institution'),
            ('fr', 'clermont university', 'institution'),
            ('ae', 'khalifa university', 'institution'),
            ('eg', 'assiut university', 'institution'),
            ('cn', 'southeast university', 'institution'),
            ('fr', 'universite laboratoire', 'institution'),
            ('eg', 'cairo university', 'institution'),
            ('cz', 'palacky university', 'institution'),
            ('jp', 'gifu university', 'institution'),
            ('fr', 'universite picardie', 'institution'),
            ('de', 'bielefeld university', 'institution'),
            ('br', 'universite federale', 'institution'),
            ('tr', 'sabanci university', 'institution'),
            ('dz', 'universite badji', 'institution'),
            ('gb', 'aston university', 'institution'),
            ('fr', 'lorraine university', 'institution'),
            ('gb', 'swansea university', 'institution'),
            ('it', 'humanitas university', 'institution'),
            ('kr', 'hallym university', 'institution'),
            ('au', 'rmit university', 'institution'),
            ('fr', 'universite ecole', 'institution'),
            ('fr', 'universite aix', 'institution')
        ON CONFLICT (form_normalized) DO NOTHING
        """
    )


def downgrade() -> None:
    # Seed additif idempotent (ON CONFLICT DO NOTHING) ; pas de retrait ciblé
    # (les formes ne sont pas distinguables de la 1re fournée). Un reset complet
    # des institutions se fait en redescendant sous la migration de seed initiale.
    pass
