"""Référentiel des domaines HAL : code stable → libellé human-readable.

HAL est la seule source pour laquelle on stocke en dur un référentiel
de sujets côté domaine. Raison : les codes CCSD que HAL expose
(`info`, `chim.anal`, `sdv.bbm.bm`…) sont opaques et exigent un
lookup pour produire un libellé affichable. Les autres sources
(OpenAlex, WoS, ScanR, theses.fr) exposent directement leurs sujets
sous forme de libellés dans leurs payloads, donc pas besoin de
table de correspondance en mémoire.

Le dict `HAL_DOMAINS` est généré depuis l'API officielle CCSD via
`interfaces/cli/dev/refresh_hal_domain_labels.py`. La hiérarchie n'est pas
stockée explicitement : elle se reconstitue à partir du code lui-même
(séparateur `.`), évitant la duplication de l'arborescence.

Usage :
    from domain.sources.hal_domains import hal_domain_label
    hal_domain_label("chim.anal")   # -> "Chimie analytique"

Si un code est inconnu (HAL a ajouté un domaine entre deux régénérations
du fichier), les helpers retournent le code tel quel — le pipeline reste
fonctionnel, juste un peu moins lisible jusqu'à la prochaine régénération.
"""

# Chaque entrée : code → libellé feuille (dernier segment du chemin
# hiérarchique HAL, annotations entre crochets retirées).
HAL_DOMAINS: dict[str, str] = {
    "chim": "Chimie",
    "chim.anal": "Chimie analytique",
    "chim.cata": "Catalyse",
    "chim.chem": "Chemo-informatique",
    "chim.coor": "Chimie de coordination",
    "chim.cris": "Cristallographie",
    "chim.geni": "Génie chimique",
    "chim.inor": "Chimie inorganique",
    "chim.mate": "Matériaux",
    "chim.orga": "Chimie organique",
    "chim.othe": "Autre",
    "chim.poly": "Polymères",
    "chim.radio": "Radiochimie",
    "chim.theo": "Chimie théorique et/ou physique",
    "chim.ther": "Chimie thérapeutique",
    "info": "Informatique",
    "info.eiah": "Environnements Informatiques pour l'Apprentissage Humain",
    "info.info-ai": "Intelligence artificielle",
    "info.info-ao": "Arithmétique des ordinateurs",
    "info.info-ar": "Architectures Matérielles",
    "info.info-au": "Automatique",
    "info.info-bi": "Bio-informatique",
    "info.info-bt": "Biotechnologie",
    "info.info-cc": "Complexité",
    "info.info-ce": "Ingénierie, finance et science",
    "info.info-cg": "Géométrie algorithmique",
    "info.info-cl": "Informatique et langage",
    "info.info-cr": "Cryptographie et sécurité",
    "info.info-cv": "Vision par ordinateur et reconnaissance de formes",
    "info.info-cy": "Ordinateur et société",
    "info.info-db": "Base de données",
    "info.info-dc": "Calcul parallèle, distribué et partagé",
    "info.info-dl": "Bibliothèque électronique",
    "info.info-dm": "Mathématique discrète",
    "info.info-ds": "Algorithme et structure de données",
    "info.info-es": "Systèmes embarqués",
    "info.info-et": "Technologies Émergeantes",
    "info.info-fl": "Théorie et langage formel",
    "info.info-gl": "Littérature générale",
    "info.info-gr": "Synthèse d'image et réalité virtuelle",
    "info.info-gt": "Informatique et théorie des jeux",
    "info.info-hc": "Interface homme-machine",
    "info.info-ia": "Ingénierie assistée par ordinateur",
    "info.info-im": "Imagerie médicale",
    "info.info-ir": "Recherche d'information",
    "info.info-it": "Théorie de l'information",
    "info.info-iu": "Informatique ubiquitaire",
    "info.info-lg": "Apprentissage",
    "info.info-lo": "Logique en informatique",
    "info.info-ma": "Système multi-agents",
    "info.info-mc": "Informatique mobile",
    "info.info-mm": "Multimédia",
    "info.info-mo": "Modélisation et simulation",
    "info.info-ms": "Logiciel mathématique",
    "info.info-na": "Analyse numérique",
    "info.info-ne": "Réseau de neurones",
    "info.info-ni": "Réseaux et télécommunications",
    "info.info-oh": "Autre",
    "info.info-os": "Système d'exploitation",
    "info.info-pf": "Performance et fiabilité",
    "info.info-pl": "Langage de programmation",
    "info.info-rb": "Robotique",
    "info.info-ro": "Recherche opérationnelle",
    "info.info-sc": "Calcul formel",
    "info.info-sd": "Son",
    "info.info-se": "Génie logiciel",
    "info.info-si": "Réseaux sociaux et d'information",
    "info.info-sy": "Systèmes et contrôle",
    "info.info-ti": "Traitement des images",
    "info.info-ts": "Traitement du signal et de l'image",
    "info.info-tt": "Traitement du texte et du document",
    "info.info-wb": "Web",
    "math": "Mathématiques",
    "math.math-ac": "Algèbre commutative",
    "math.math-ag": "Géométrie algébrique",
    "math.math-ap": "Equations aux dérivées partielles",
    "math.math-at": "Topologie algébrique",
    "math.math-ca": "Analyse classique",
    "math.math-co": "Combinatoire",
    "math.math-ct": "Catégories et ensembles",
    "math.math-cv": "Variables complexes",
    "math.math-dg": "Géométrie différentielle",
    "math.math-ds": "Systèmes dynamiques",
    "math.math-fa": "Analyse fonctionnelle",
    "math.math-gm": "Mathématiques générales",
    "math.math-gn": "Topologie générale",
    "math.math-gr": "Théorie des groupes",
    "math.math-gt": "Topologie géométrique",
    "math.math-ho": "Histoire et perspectives sur les mathématiques",
    "math.math-it": "Théorie de l'information et codage",
    "math.math-kt": "K-théorie et homologie",
    "math.math-lo": "Logique",
    "math.math-mg": "Géométrie métrique",
    "math.math-mp": "Physique mathématique",
    "math.math-na": "Analyse numérique",
    "math.math-nt": "Théorie des nombres",
    "math.math-oa": "Algèbres d'opérateurs",
    "math.math-oc": "Optimisation et contrôle",
    "math.math-pr": "Probabilités",
    "math.math-qa": "Algèbres quantiques",
    "math.math-ra": "Anneaux et algèbres",
    "math.math-rt": "Théorie des représentations",
    "math.math-sg": "Géométrie symplectique",
    "math.math-sp": "Théorie spectrale",
    "math.math-st": "Statistiques",
    "nlin": "Science non linéaire",
    "nlin.nlin-ao": "Adaptation et Systèmes auto-organisés",
    "nlin.nlin-cd": "Dynamique Chaotique",
    "nlin.nlin-cg": "Automates cellulaires et gaz sur réseau",
    "nlin.nlin-ps": "Formation de Structures et Solitons",
    "nlin.nlin-si": "Systèmes Solubles et Intégrables",
    "phys": "Physique",
    "phys.astr": "Astrophysique",
    "phys.astr.co": "Cosmologie et astrophysique extra-galactique",
    "phys.astr.ep": "Planétologie et astrophysique de la terre",
    "phys.astr.ga": "Astrophysique galactique",
    "phys.astr.he": "Phénomènes cosmiques de haute energie",
    "phys.astr.im": "Instrumentation et méthodes pour l'astrophysique",
    "phys.astr.sr": "Astrophysique stellaire et solaire",
    "phys.cond": "Matière Condensée",
    "phys.cond.cm-ds-nn": "Systèmes désordonnés et réseaux de neurones",
    "phys.cond.cm-gen": "Autre",
    "phys.cond.cm-ms": "Science des matériaux",
    "phys.cond.cm-msqhe": "Systèmes mésoscopiques et effet Hall quantique",
    "phys.cond.cm-s": "Supraconductivité",
    "phys.cond.cm-sce": "Electrons fortement corrélés",
    "phys.cond.cm-scm": "Matière Molle",
    "phys.cond.cm-sm": "Mécanique statistique",
    "phys.cond.gas": "Gaz Quantiques",
    "phys.grqc": "Relativité Générale et Cosmologie Quantique",
    "phys.hexp": "Physique des Hautes Energies - Expérience",
    "phys.hist": "Articles anciens",
    "phys.hlat": "Physique des Hautes Energies - Réseau",
    "phys.hphe": "Physique des Hautes Energies - Phénoménologie",
    "phys.hthe": "Physique des Hautes Energies - Théorie",
    "phys.meca": "Mécanique",
    "phys.meca.acou": "Acoustique",
    "phys.meca.biom": "Biomécanique",
    "phys.meca.geme": "Génie mécanique",
    "phys.meca.mefl": "Mécanique des fluides",
    "phys.meca.mema": "Mécanique des matériaux",
    "phys.meca.msmeca": "Matériaux et structures en mécanique",
    "phys.meca.solid": "Mécanique des solides",
    "phys.meca.stru": "Mécanique des structures",
    "phys.meca.ther": "Thermique",
    "phys.meca.vibr": "Vibrations",
    "phys.mphy": "Physique mathématique",
    "phys.nexp": "Physique Nucléaire Expérimentale",
    "phys.nucl": "Physique Nucléaire Théorique",
    "phys.phys": "Physique",
    "phys.phys.phys-acc-ph": "Physique des accélérateurs",
    "phys.phys.phys-ao-ph": "Physique Atmosphérique et Océanique",
    "phys.phys.phys-atm-ph": "Agrégats Moléculaires et Atomiques",
    "phys.phys.phys-atom-ph": "Physique Atomique",
    "phys.phys.phys-bio-ph": "Biophysique",
    "phys.phys.phys-chem-ph": "Chimie-Physique",
    "phys.phys.phys-class-ph": "Physique Classique",
    "phys.phys.phys-comp-ph": "Physique Numérique",
    "phys.phys.phys-data-an": "Analyse de données, Statistiques et Probabilités",
    "phys.phys.phys-ed-ph": "Enseignement de la physique",
    "phys.phys.phys-flu-dyn": "Dynamique des Fluides",
    "phys.phys.phys-gen-ph": "Physique Générale",
    "phys.phys.phys-geo-ph": "Géophysique",
    "phys.phys.phys-hist-ph": "Histoire de la Physique",
    "phys.phys.phys-ins-det": "Instrumentations et Détecteurs",
    "phys.phys.phys-med-ph": "Physique Médicale",
    "phys.phys.phys-optics": "Optique",
    "phys.phys.phys-plasm-ph": "Physique des plasmas",
    "phys.phys.phys-pop-ph": "Physique : vulgarisation",
    "phys.phys.phys-soc-ph": "Physique et Société",
    "phys.phys.phys-space-ph": "Physique de l'espace",
    "phys.qphy": "Physique Quantique",
    "qfin": "Économie et finance quantitative",
    "qfin.cp": "Finance quantitative",
    "qfin.gn": "Finance",
    "qfin.pm": "Gestion de portefeuilles",
    "qfin.pr": "Pricing",
    "qfin.rm": "Gestion des risques",
    "qfin.st": "Econométrie de la finance",
    "qfin.tr": "Microstructure des marchés",
    "scco": "Sciences cognitives",
    "scco.comp": "Informatique",
    "scco.ling": "Linguistique",
    "scco.neur": "Neurosciences",
    "scco.psyc": "Psychologie",
    "sde": "Sciences de l'environnement",
    "sde.be": "Biodiversité et Ecologie",
    "sde.es": "Environnement et Société",
    "sde.ie": "Ingénierie de l'environnement",
    "sde.mcg": "Milieux et Changements globaux",
    "sdu": "Planète et Univers",
    "sdu.astr": "Astrophysique",
    "sdu.astr.co": "Cosmologie et astrophysique extra-galactique",
    "sdu.astr.ep": "Planétologie et astrophysique de la terre",
    "sdu.astr.ga": "Astrophysique galactique",
    "sdu.astr.he": "Phénomènes cosmiques de haute energie",
    "sdu.astr.im": "Instrumentation et méthodes pour l'astrophysique",
    "sdu.astr.sr": "Astrophysique stellaire et solaire",
    "sdu.envi": "Interfaces continentales, environnement",
    "sdu.ocean": "Océan, Atmosphère",
    "sdu.other": "Autre",
    "sdu.stu": "Sciences de la Terre",
    "sdu.stu.ag": "Géologie appliquée",
    "sdu.stu.cl": "Climatologie",
    "sdu.stu.gc": "Géochimie",
    "sdu.stu.gl": "Glaciologie",
    "sdu.stu.gm": "Géomorphologie",
    "sdu.stu.gp": "Géophysique",
    "sdu.stu.hy": "Hydrologie",
    "sdu.stu.me": "Météorologie",
    "sdu.stu.mi": "Minéralogie",
    "sdu.stu.oc": "Océanographie",
    "sdu.stu.pe": "Pétrographie",
    "sdu.stu.pg": "Paléontologie",
    "sdu.stu.pl": "Planétologie",
    "sdu.stu.st": "Stratigraphie",
    "sdu.stu.te": "Tectonique",
    "sdu.stu.vo": "Volcanologie",
    "sdv": "Sciences du Vivant",
    "sdv.aen": "Alimentation et Nutrition",
    "sdv.ba": "Biologie animale",
    "sdv.ba.mvsa": "Médecine vétérinaire et santé animale",
    "sdv.ba.zi": "Zoologie des invertébrés",
    "sdv.ba.zv": "Zoologie des vertébrés",
    "sdv.bbm": "Biochimie, Biologie Moléculaire",
    "sdv.bbm.bc": "Biochimie",
    "sdv.bbm.bm": "Biologie moléculaire",
    "sdv.bbm.bp": "Biophysique",
    "sdv.bbm.bs": "Biologie structurale",
    "sdv.bbm.gtp": "Génomique, Transcriptomique et Protéomique",
    "sdv.bbm.mn": "Réseaux moléculaires",
    "sdv.bc": "Biologie cellulaire",
    "sdv.bc.bc": "Organisation et fonctions cellulaires",
    "sdv.bc.ic": "Interactions cellulaires",
    "sdv.bdd": "Biologie du développement",
    "sdv.bdd.eo": "Embryologie et organogenèse",
    "sdv.bdd.gam": "Gamétogenèse",
    "sdv.bdd.mor": "Morphogenèse",
    "sdv.bdlr": "Biologie de la reproduction",
    "sdv.bdlr.ra": "Reproduction asexuée",
    "sdv.bdlr.rs": "Reproduction sexuée",
    "sdv.bibs": "Bio-Informatique, Biologie Systémique",
    "sdv.bid": "Biodiversité",
    "sdv.bid.evo": "Evolution",
    "sdv.bid.spt": "Systématique, phylogénie et taxonomie",
    "sdv.bio": "Biotechnologies",
    "sdv.bv": "Biologie végétale",
    "sdv.bv.ap": "Amélioration des plantes",
    "sdv.bv.bot": "Botanique",
    "sdv.bv.pep": "Phytopathologie et phytopharmacie",
    "sdv.can": "Cancer",
    "sdv.ee": "Ecologie, Environnement",
    "sdv.ee.bio": "Bioclimatologie",
    "sdv.ee.eco": "Ecosystèmes",
    "sdv.ee.ieo": "Interactions entre organismes",
    "sdv.ee.sant": "Santé",
    "sdv.eth": "Ethique",
    "sdv.gen": "Génétique",
    "sdv.gen.ga": "Génétique animale",
    "sdv.gen.gh": "Génétique humaine",
    "sdv.gen.gpl": "Génétique des plantes",
    "sdv.gen.gpo": "Génétique des populations",
    "sdv.ib": "Ingénierie biomédicale",
    "sdv.ib.bio": "Biomatériaux",
    "sdv.ib.ima": "Imagerie",
    "sdv.ib.mn": "Médecine nucléaire",
    "sdv.ida": "Ingénierie des aliments",
    "sdv.imm": "Immunologie",
    "sdv.imm.all": "Allergologie",
    "sdv.imm.ia": "Immunité adaptative",
    "sdv.imm.ii": "Immunité innée",
    "sdv.imm.imm": "Immunothérapie",
    "sdv.imm.vac": "Vaccinologie",
    "sdv.mhep": "Médecine humaine et pathologie",
    "sdv.mhep.aha": "Anatomie, Histologie, Anatomopathologie",
    "sdv.mhep.chi": "Chirurgie",
    "sdv.mhep.csc": "Cardiologie et système cardiovasculaire",
    "sdv.mhep.derm": "Dermatologie",
    "sdv.mhep.em": "Endocrinologie et métabolisme",
    "sdv.mhep.geg": "Gériatrie et gérontologie",
    "sdv.mhep.geo": "Gynécologie et obstétrique",
    "sdv.mhep.heg": "Hépatologie et Gastroentérologie",
    "sdv.mhep.hem": "Hématologie",
    "sdv.mhep.me": "Maladies émergentes",
    "sdv.mhep.mi": "Maladies infectieuses",
    "sdv.mhep.os": "Organes des sens",
    "sdv.mhep.ped": "Pédiatrie",
    "sdv.mhep.phy": "Physiologie",
    "sdv.mhep.psm": "Psychiatrie et santé mentale",
    "sdv.mhep.psr": "Pneumologie et système respiratoire",
    "sdv.mhep.rsoa": "Rhumatologie et système ostéo-articulaire",
    "sdv.mhep.un": "Urologie et Néphrologie",
    "sdv.mp": "Microbiologie et Parasitologie",
    "sdv.mp.bac": "Bactériologie",
    "sdv.mp.myc": "Mycologie",
    "sdv.mp.par": "Parasitologie",
    "sdv.mp.pro": "Protistologie",
    "sdv.mp.vir": "Virologie",
    "sdv.neu": "Neurosciences",
    "sdv.neu.nb": "Neurobiologie",
    "sdv.neu.pc": "Psychologie et comportements",
    "sdv.neu.sc": "Sciences cognitives",
    "sdv.ot": "Autre",
    "sdv.sa": "Sciences agricoles",
    "sdv.sa.aep": "Agriculture, économie et politique",
    "sdv.sa.agro": "Agronomie",
    "sdv.sa.hort": "Horticulture",
    "sdv.sa.sds": "Science des sols",
    "sdv.sa.sf": "Sylviculture, foresterie",
    "sdv.sa.spa": "Science des productions animales",
    "sdv.sa.sta": "Sciences et techniques de l'agriculture",
    "sdv.sa.stp": "Sciences et techniques des pêches",
    "sdv.sa.zoo": "Zootechnie",
    "sdv.sp": "Sciences pharmaceutiques",
    "sdv.sp.med": "Médicaments",
    "sdv.sp.pg": "Pharmacie galénique",
    "sdv.sp.pharma": "Pharmacologie",
    "sdv.spee": "Santé publique et épidémiologie",
    "sdv.tox": "Toxicologie",
    "sdv.tox.eco": "Ecotoxicologie",
    "sdv.tox.tca": "Toxicologie et chaîne alimentaire",
    "sdv.tox.tvm": "Toxicologie végétale et mycotoxicologie",
    "shs": "Sciences de l'Homme et Société",
    "shs.anthro-bio": "Anthropologie biologique",
    "shs.anthro-se": "Anthropologie sociale et ethnologie",
    "shs.archeo": "Archéologie et Préhistoire",
    "shs.archi": "Architecture, aménagement de l'espace",
    "shs.art": "Art et histoire de l'art",
    "shs.class": "Etudes classiques",
    "shs.demo": "Démographie",
    "shs.droit": "Droit",
    "shs.eco": "Economies et finances",
    "shs.edu": "Education",
    "shs.envir": "Etudes de l'environnement",
    "shs.genre": "Etudes sur le genre",
    "shs.geo": "Géographie",
    "shs.gestion": "Gestion et management",
    "shs.hisphilso": "Histoire, Philosophie et Sociologie des sciences",
    "shs.hist": "Histoire",
    "shs.info": "Sciences de l'information et de la communication",
    "shs.langue": "Linguistique",
    "shs.litt": "Littératures",
    "shs.museo": "Héritage culturel et muséologie",
    "shs.musiq": "Musique, musicologie et arts de la scène",
    "shs.phil": "Philosophie",
    "shs.psy": "Psychologie",
    "shs.relig": "Religions",
    "shs.scipo": "Science politique",
    "shs.socio": "Sociologie",
    "shs.stat": "Méthodes et statistiques",
    "spi": "Sciences de l'ingénieur",
    "spi.acou": "Acoustique",
    "spi.auto": "Automatique / Robotique",
    "spi.elec": "Electromagnétisme",
    "spi.fluid": "Milieux fluides et réactifs",
    "spi.gciv": "Génie civil",
    "spi.gciv.cd": "Construction durable",
    "spi.gciv.ch": "Construction hydraulique",
    "spi.gciv.dv": "Dynamique, vibrations",
    "spi.gciv.ec": "Eco-conception",
    "spi.gciv.gcn": "Génie civil nucléaire",
    "spi.gciv.geotech": "Géotechnique",
    "spi.gciv.it": "Infrastructures de transport",
    "spi.gciv.mat": "Matériaux composites et construction",
    "spi.gciv.rhea": "Réhabilitation",
    "spi.gciv.risq": "Risques",
    "spi.gciv.struct": "Structures",
    "spi.gproc": "Génie des procédés",
    "spi.mat": "Matériaux",
    "spi.meca": "Mécanique",
    "spi.meca.biom": "Biomécanique",
    "spi.meca.geme": "Génie mécanique",
    "spi.meca.mefl": "Mécanique des fluides",
    "spi.meca.mema": "Mécanique des matériaux",
    "spi.meca.msmeca": "Matériaux et structures en mécanique",
    "spi.meca.solid": "Mécanique des solides",
    "spi.meca.stru": "Mécanique des structures",
    "spi.meca.ther": "Thermique",
    "spi.meca.vibr": "Vibrations",
    "spi.nano": "Micro et nanotechnologies/Microélectronique",
    "spi.nrj": "Energie électrique",
    "spi.opti": "Optique / photonique",
    "spi.other": "Autre",
    "spi.plasma": "Plasmas",
    "spi.signal": "Traitement du signal et de l'image",
    "spi.tron": "Electronique",
    "stat": "Statistiques",
    "stat.ap": "Applications",
    "stat.co": "Calcul",
    "stat.me": "Méthodologie",
    "stat.ml": "Machine Learning",
    "stat.ot": "Autres",
    "stat.th": "Théorie",
}


def hal_domain_label(code: str) -> str:
    """Libellé human-readable d'un domaine HAL (feuille).

    Fallback sur le code lui-même si inconnu.
    """
    return HAL_DOMAINS.get(code, code)
