-- Seed généré automatiquement par interfaces/cli/dev/generate_seed.py
-- Ne pas modifier à la main — relancer le script pour régénérer.
--
-- Seed commun : référentiels partagés par tous les établissements.
-- Prérequis : schéma appliqué par les migrations (alembic upgrade head)
-- Usage : psql -d bibliometrie -f infrastructure/db/seed.sql

BEGIN;

-- config (4 lignes)
DELETE FROM config WHERE key NOT IN ('perimeter_extraction', 'perimeter_persons');
INSERT INTO config (key, value, description) VALUES ('fetch_missing_max_per_source', '10000', 'Nombre maximum de DOI interrogés par source cible au cross-import, par run. 0 = illimité.');
INSERT INTO config (key, value, description) VALUES ('laboratories_display_types', '["labo", "admin"]', 'Types de structure affichés sur la page publique des laboratoires');
INSERT INTO config (key, value, description) VALUES ('pipeline_start_year_full', '2017', 'Mode full/monthly : extraire depuis cette année (incluse) jusqu''à l''année courante. Année absolue (ancre fixe), pas un offset — rétention cumulative.');
INSERT INTO config (key, value, description) VALUES ('unpaywall_max_per_run', '10000', 'Nombre maximum de DOI vérifiés auprès d''Unpaywall par run. 0 = illimité.');

-- countries (175 lignes)
DELETE FROM countries;
INSERT INTO countries (code, name) VALUES ('ad', 'Andorre');
INSERT INTO countries (code, name) VALUES ('ae', 'Émirats arabes unis');
INSERT INTO countries (code, name) VALUES ('af', 'Afghanistan');
INSERT INTO countries (code, name) VALUES ('ag', 'Antigua-et-Barbuda');
INSERT INTO countries (code, name) VALUES ('al', 'Albanie');
INSERT INTO countries (code, name) VALUES ('am', 'Arménie');
INSERT INTO countries (code, name) VALUES ('ao', 'Angola');
INSERT INTO countries (code, name) VALUES ('ar', 'Argentine');
INSERT INTO countries (code, name) VALUES ('at', 'Autriche');
INSERT INTO countries (code, name) VALUES ('au', 'Australie');
INSERT INTO countries (code, name) VALUES ('az', 'Azerbaïdjan');
INSERT INTO countries (code, name) VALUES ('ba', 'Bosnie-Herzégovine');
INSERT INTO countries (code, name) VALUES ('bb', 'Barbade');
INSERT INTO countries (code, name) VALUES ('bd', 'Bangladesh');
INSERT INTO countries (code, name) VALUES ('be', 'Belgique');
INSERT INTO countries (code, name) VALUES ('bf', 'Burkina Faso');
INSERT INTO countries (code, name) VALUES ('bg', 'Bulgarie');
INSERT INTO countries (code, name) VALUES ('bh', 'Bahreïn');
INSERT INTO countries (code, name) VALUES ('bi', 'Burundi');
INSERT INTO countries (code, name) VALUES ('bj', 'Bénin');
INSERT INTO countries (code, name) VALUES ('bn', 'Brunei');
INSERT INTO countries (code, name) VALUES ('bo', 'Bolivie');
INSERT INTO countries (code, name) VALUES ('br', 'Brésil');
INSERT INTO countries (code, name) VALUES ('bs', 'Bahamas');
INSERT INTO countries (code, name) VALUES ('bt', 'Bhoutan');
INSERT INTO countries (code, name) VALUES ('bw', 'Botswana');
INSERT INTO countries (code, name) VALUES ('by', 'Biélorussie');
INSERT INTO countries (code, name) VALUES ('bz', 'Belize');
INSERT INTO countries (code, name) VALUES ('ca', 'Canada');
INSERT INTO countries (code, name) VALUES ('cd', 'Rép. dém. du Congo');
INSERT INTO countries (code, name) VALUES ('cf', 'Centrafrique');
INSERT INTO countries (code, name) VALUES ('cg', 'Congo');
INSERT INTO countries (code, name) VALUES ('ch', 'Suisse');
INSERT INTO countries (code, name) VALUES ('ci', 'Côte d''Ivoire');
INSERT INTO countries (code, name) VALUES ('cl', 'Chili');
INSERT INTO countries (code, name) VALUES ('cm', 'Cameroun');
INSERT INTO countries (code, name) VALUES ('cn', 'Chine');
INSERT INTO countries (code, name) VALUES ('co', 'Colombie');
INSERT INTO countries (code, name) VALUES ('cr', 'Costa Rica');
INSERT INTO countries (code, name) VALUES ('cu', 'Cuba');
INSERT INTO countries (code, name) VALUES ('cv', 'Cap-Vert');
INSERT INTO countries (code, name) VALUES ('cy', 'Chypre');
INSERT INTO countries (code, name) VALUES ('cz', 'Tchéquie');
INSERT INTO countries (code, name) VALUES ('de', 'Allemagne');
INSERT INTO countries (code, name) VALUES ('dj', 'Djibouti');
INSERT INTO countries (code, name) VALUES ('dk', 'Danemark');
INSERT INTO countries (code, name) VALUES ('dm', 'Dominique');
INSERT INTO countries (code, name) VALUES ('do', 'Rép. dominicaine');
INSERT INTO countries (code, name) VALUES ('dz', 'Algérie');
INSERT INTO countries (code, name) VALUES ('ec', 'Équateur');
INSERT INTO countries (code, name) VALUES ('ee', 'Estonie');
INSERT INTO countries (code, name) VALUES ('eg', 'Égypte');
INSERT INTO countries (code, name) VALUES ('er', 'Érythrée');
INSERT INTO countries (code, name) VALUES ('es', 'Espagne');
INSERT INTO countries (code, name) VALUES ('et', 'Éthiopie');
INSERT INTO countries (code, name) VALUES ('fi', 'Finlande');
INSERT INTO countries (code, name) VALUES ('fj', 'Fidji');
INSERT INTO countries (code, name) VALUES ('fr', 'France');
INSERT INTO countries (code, name) VALUES ('ga', 'Gabon');
INSERT INTO countries (code, name) VALUES ('gb', 'Royaume-Uni');
INSERT INTO countries (code, name) VALUES ('gd', 'Grenade');
INSERT INTO countries (code, name) VALUES ('ge', 'Géorgie');
INSERT INTO countries (code, name) VALUES ('gh', 'Ghana');
INSERT INTO countries (code, name) VALUES ('gm', 'Gambie');
INSERT INTO countries (code, name) VALUES ('gn', 'Guinée');
INSERT INTO countries (code, name) VALUES ('gq', 'Guinée équatoriale');
INSERT INTO countries (code, name) VALUES ('gr', 'Grèce');
INSERT INTO countries (code, name) VALUES ('gt', 'Guatemala');
INSERT INTO countries (code, name) VALUES ('gw', 'Guinée-Bissau');
INSERT INTO countries (code, name) VALUES ('gy', 'Guyana');
INSERT INTO countries (code, name) VALUES ('hn', 'Honduras');
INSERT INTO countries (code, name) VALUES ('hr', 'Croatie');
INSERT INTO countries (code, name) VALUES ('ht', 'Haïti');
INSERT INTO countries (code, name) VALUES ('hu', 'Hongrie');
INSERT INTO countries (code, name) VALUES ('id', 'Indonésie');
INSERT INTO countries (code, name) VALUES ('ie', 'Irlande');
INSERT INTO countries (code, name) VALUES ('il', 'Israël');
INSERT INTO countries (code, name) VALUES ('in', 'Inde');
INSERT INTO countries (code, name) VALUES ('iq', 'Irak');
INSERT INTO countries (code, name) VALUES ('ir', 'Iran');
INSERT INTO countries (code, name) VALUES ('is', 'Islande');
INSERT INTO countries (code, name) VALUES ('it', 'Italie');
INSERT INTO countries (code, name) VALUES ('jm', 'Jamaïque');
INSERT INTO countries (code, name) VALUES ('jo', 'Jordanie');
INSERT INTO countries (code, name) VALUES ('jp', 'Japon');
INSERT INTO countries (code, name) VALUES ('ke', 'Kenya');
INSERT INTO countries (code, name) VALUES ('kg', 'Kirghizistan');
INSERT INTO countries (code, name) VALUES ('kh', 'Cambodge');
INSERT INTO countries (code, name) VALUES ('kr', 'Corée du Sud');
INSERT INTO countries (code, name) VALUES ('kw', 'Koweït');
INSERT INTO countries (code, name) VALUES ('kz', 'Kazakhstan');
INSERT INTO countries (code, name) VALUES ('la', 'Laos');
INSERT INTO countries (code, name) VALUES ('lb', 'Liban');
INSERT INTO countries (code, name) VALUES ('lk', 'Sri Lanka');
INSERT INTO countries (code, name) VALUES ('lr', 'Liberia');
INSERT INTO countries (code, name) VALUES ('ls', 'Lesotho');
INSERT INTO countries (code, name) VALUES ('lt', 'Lituanie');
INSERT INTO countries (code, name) VALUES ('lu', 'Luxembourg');
INSERT INTO countries (code, name) VALUES ('lv', 'Lettonie');
INSERT INTO countries (code, name) VALUES ('ly', 'Libye');
INSERT INTO countries (code, name) VALUES ('ma', 'Maroc');
INSERT INTO countries (code, name) VALUES ('mc', 'Monaco');
INSERT INTO countries (code, name) VALUES ('md', 'Moldavie');
INSERT INTO countries (code, name) VALUES ('me', 'Monténégro');
INSERT INTO countries (code, name) VALUES ('mg', 'Madagascar');
INSERT INTO countries (code, name) VALUES ('mk', 'Macédoine du Nord');
INSERT INTO countries (code, name) VALUES ('ml', 'Mali');
INSERT INTO countries (code, name) VALUES ('mm', 'Myanmar');
INSERT INTO countries (code, name) VALUES ('mn', 'Mongolie');
INSERT INTO countries (code, name) VALUES ('mr', 'Mauritanie');
INSERT INTO countries (code, name) VALUES ('mt', 'Malte');
INSERT INTO countries (code, name) VALUES ('mu', 'Maurice');
INSERT INTO countries (code, name) VALUES ('mv', 'Maldives');
INSERT INTO countries (code, name) VALUES ('mw', 'Malawi');
INSERT INTO countries (code, name) VALUES ('mx', 'Mexique');
INSERT INTO countries (code, name) VALUES ('my', 'Malaisie');
INSERT INTO countries (code, name) VALUES ('mz', 'Mozambique');
INSERT INTO countries (code, name) VALUES ('na', 'Namibie');
INSERT INTO countries (code, name) VALUES ('ne', 'Niger');
INSERT INTO countries (code, name) VALUES ('ng', 'Nigeria');
INSERT INTO countries (code, name) VALUES ('ni', 'Nicaragua');
INSERT INTO countries (code, name) VALUES ('nl', 'Pays-Bas');
INSERT INTO countries (code, name) VALUES ('no', 'Norvège');
INSERT INTO countries (code, name) VALUES ('np', 'Népal');
INSERT INTO countries (code, name) VALUES ('nz', 'Nouvelle-Zélande');
INSERT INTO countries (code, name) VALUES ('om', 'Oman');
INSERT INTO countries (code, name) VALUES ('pa', 'Panama');
INSERT INTO countries (code, name) VALUES ('pe', 'Pérou');
INSERT INTO countries (code, name) VALUES ('pg', 'Papouasie-Nouvelle-Guinée');
INSERT INTO countries (code, name) VALUES ('ph', 'Philippines');
INSERT INTO countries (code, name) VALUES ('pk', 'Pakistan');
INSERT INTO countries (code, name) VALUES ('pl', 'Pologne');
INSERT INTO countries (code, name) VALUES ('ps', 'Palestine');
INSERT INTO countries (code, name) VALUES ('pt', 'Portugal');
INSERT INTO countries (code, name) VALUES ('py', 'Paraguay');
INSERT INTO countries (code, name) VALUES ('qa', 'Qatar');
INSERT INTO countries (code, name) VALUES ('ro', 'Roumanie');
INSERT INTO countries (code, name) VALUES ('rs', 'Serbie');
INSERT INTO countries (code, name) VALUES ('ru', 'Russie');
INSERT INTO countries (code, name) VALUES ('rw', 'Rwanda');
INSERT INTO countries (code, name) VALUES ('sa', 'Arabie saoudite');
INSERT INTO countries (code, name) VALUES ('sd', 'Soudan');
INSERT INTO countries (code, name) VALUES ('se', 'Suède');
INSERT INTO countries (code, name) VALUES ('sg', 'Singapour');
INSERT INTO countries (code, name) VALUES ('si', 'Slovénie');
INSERT INTO countries (code, name) VALUES ('sk', 'Slovaquie');
INSERT INTO countries (code, name) VALUES ('sl', 'Sierra Leone');
INSERT INTO countries (code, name) VALUES ('sn', 'Sénégal');
INSERT INTO countries (code, name) VALUES ('so', 'Somalie');
INSERT INTO countries (code, name) VALUES ('ss', 'Soudan du Sud');
INSERT INTO countries (code, name) VALUES ('sv', 'Salvador');
INSERT INTO countries (code, name) VALUES ('sy', 'Syrie');
INSERT INTO countries (code, name) VALUES ('td', 'Tchad');
INSERT INTO countries (code, name) VALUES ('tg', 'Togo');
INSERT INTO countries (code, name) VALUES ('th', 'Thaïlande');
INSERT INTO countries (code, name) VALUES ('tj', 'Tadjikistan');
INSERT INTO countries (code, name) VALUES ('tl', 'Timor oriental');
INSERT INTO countries (code, name) VALUES ('tm', 'Turkménistan');
INSERT INTO countries (code, name) VALUES ('tn', 'Tunisie');
INSERT INTO countries (code, name) VALUES ('tr', 'Turquie');
INSERT INTO countries (code, name) VALUES ('tt', 'Trinité-et-Tobago');
INSERT INTO countries (code, name) VALUES ('tw', 'Taïwan');
INSERT INTO countries (code, name) VALUES ('tz', 'Tanzanie');
INSERT INTO countries (code, name) VALUES ('ua', 'Ukraine');
INSERT INTO countries (code, name) VALUES ('ug', 'Ouganda');
INSERT INTO countries (code, name) VALUES ('us', 'États-Unis');
INSERT INTO countries (code, name) VALUES ('uy', 'Uruguay');
INSERT INTO countries (code, name) VALUES ('uz', 'Ouzbékistan');
INSERT INTO countries (code, name) VALUES ('ve', 'Venezuela');
INSERT INTO countries (code, name) VALUES ('vn', 'Viêt Nam');
INSERT INTO countries (code, name) VALUES ('xx', 'Non applicable');
INSERT INTO countries (code, name) VALUES ('ye', 'Yémen');
INSERT INTO countries (code, name) VALUES ('za', 'Afrique du Sud');
INSERT INTO countries (code, name) VALUES ('zm', 'Zambie');
INSERT INTO countries (code, name) VALUES ('zw', 'Zimbabwe');

-- place_name_forms (509 lignes)
DELETE FROM place_name_forms WHERE kind <> 'institution';
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (1, 'fr', 'france', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (3, 'fr', 'fra', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (4, 'fr', 'francia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (5, 'de', 'germany', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (6, 'de', 'allemagne', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (7, 'de', 'deutschland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (8, 'de', 'fed rep ger', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (9, 'gb', 'uk', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (10, 'gb', 'united kingdom', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (11, 'gb', 'england', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (12, 'gb', 'scotland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (13, 'gb', 'wales', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (14, 'gb', 'great britain', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (15, 'gb', 'royaume-uni', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (16, 'gb', 'royaume uni', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (17, 'it', 'italy', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (18, 'it', 'italie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (19, 'it', 'italia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (20, 'es', 'spain', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (21, 'es', 'espagne', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (22, 'es', 'espana', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (23, 'pt', 'portugal', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (24, 'nl', 'netherlands', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (25, 'nl', 'the netherlands', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (26, 'nl', 'pays-bas', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (27, 'nl', 'pays bas', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (28, 'nl', 'holland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (29, 'be', 'belgium', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (30, 'be', 'belgique', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (31, 'be', 'belgie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (32, 'lu', 'luxembourg', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (33, 'ch', 'switzerland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (34, 'ch', 'suisse', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (35, 'ch', 'schweiz', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (36, 'at', 'austria', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (37, 'at', 'autriche', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (38, 'at', 'osterreich', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (39, 'ie', 'ireland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (40, 'ie', 'irlande', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (41, 'mc', 'monaco', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (42, 'se', 'sweden', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (43, 'se', 'suede', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (44, 'no', 'norway', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (45, 'no', 'norvege', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (46, 'dk', 'denmark', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (47, 'dk', 'danemark', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (48, 'fi', 'finland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (49, 'fi', 'finlande', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (50, 'is', 'iceland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (51, 'is', 'islande', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (52, 'pl', 'poland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (53, 'pl', 'pologne', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (54, 'pl', 'polska', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (55, 'cz', 'czech republic', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (56, 'cz', 'czechia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (57, 'cz', 'republique tcheque', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (58, 'sk', 'slovakia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (59, 'sk', 'slovaquie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (60, 'hu', 'hungary', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (61, 'hu', 'hongrie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (62, 'ro', 'romania', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (63, 'ro', 'roumanie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (64, 'bg', 'bulgaria', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (65, 'bg', 'bulgarie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (66, 'hr', 'croatia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (67, 'hr', 'croatie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (68, 'si', 'slovenia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (69, 'si', 'slovenie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (70, 'rs', 'serbia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (71, 'rs', 'serbie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (72, 'ba', 'bosnia and herzegovina', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (73, 'ba', 'bosnia & herzegovina', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (74, 'ba', 'bosnie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (75, 'me', 'montenegro', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (76, 'mk', 'north macedonia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (77, 'mk', 'macedonia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (78, 'al', 'albania', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (79, 'al', 'albanie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (80, 'ee', 'estonia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (81, 'ee', 'estonie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (82, 'lv', 'latvia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (83, 'lv', 'lettonie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (84, 'lt', 'lithuania', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (85, 'lt', 'lituanie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (86, 'gr', 'greece', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (87, 'gr', 'grece', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (88, 'tr', 'turkey', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (89, 'tr', 'turquie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (90, 'tr', 'turkiye', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (91, 'cy', 'cyprus', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (92, 'cy', 'chypre', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (93, 'mt', 'malta', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (94, 'mt', 'malte', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (95, 'ru', 'russia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (96, 'ru', 'russie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (97, 'ru', 'russian federation', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (98, 'ua', 'ukraine', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (99, 'by', 'belarus', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (100, 'md', 'moldova', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (101, 'ge', 'georgia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (102, 'am', 'armenia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (103, 'am', 'armenie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (104, 'az', 'azerbaijan', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (105, 'az', 'azerbaidjan', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (106, 'kz', 'kazakhstan', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (107, 'uz', 'uzbekistan', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (108, 'uz', 'ouzbekistan', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (109, 'us', 'usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (110, 'us', 'united states', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (111, 'us', 'united states of america', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (112, 'us', 'u.s.a.', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (113, 'us', 'u.s.a', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (114, 'us', 'etats-unis', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (115, 'us', 'etats unis', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (116, 'ca', 'canada', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (117, 'mx', 'mexico', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (118, 'mx', 'mexique', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (119, 'br', 'brazil', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (120, 'br', 'bresil', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (121, 'br', 'brasil', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (122, 'ar', 'argentina', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (123, 'ar', 'argentine', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (124, 'cl', 'chile', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (125, 'cl', 'chili', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (126, 'co', 'colombia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (127, 'co', 'colombie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (128, 'pe', 'peru', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (129, 'pe', 'perou', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (130, 've', 'venezuela', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (131, 'ec', 'ecuador', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (132, 'ec', 'equateur', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (133, 'uy', 'uruguay', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (134, 'py', 'paraguay', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (135, 'bo', 'bolivia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (136, 'bo', 'bolivie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (137, 'cr', 'costa rica', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (138, 'pa', 'panama', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (139, 'cu', 'cuba', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (140, 'gt', 'guatemala', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (141, 'hn', 'honduras', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (142, 'sv', 'el salvador', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (143, 'ni', 'nicaragua', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (144, 'jm', 'jamaica', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (145, 'jm', 'jamaique', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (146, 'ht', 'haiti', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (147, 'do', 'dominican republic', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (148, 'do', 'republique dominicaine', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (149, 'tt', 'trinidad and tobago', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (150, 'pr', 'puerto rico', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (151, 'pr', 'porto rico', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (152, 'cn', 'china', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (153, 'cn', 'chine', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (154, 'cn', 'peoples r china', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (155, 'cn', 'p.r. china', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (156, 'cn', 'pr china', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (157, 'jp', 'japan', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (158, 'jp', 'japon', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (159, 'kr', 'south korea', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (160, 'kr', 'korea', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (161, 'kr', 'coree du sud', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (162, 'kr', 'republic of korea', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (163, 'kp', 'north korea', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (164, 'kp', 'coree du nord', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (165, 'tw', 'taiwan', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (166, 'mn', 'mongolia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (167, 'mn', 'mongolie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (168, 'vn', 'vietnam', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (169, 'vn', 'viet nam', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (170, 'th', 'thailand', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (171, 'th', 'thailande', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (172, 'my', 'malaysia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (173, 'my', 'malaisie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (174, 'sg', 'singapore', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (175, 'sg', 'singapour', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (176, 'id', 'indonesia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (177, 'id', 'indonesie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (178, 'ph', 'philippines', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (179, 'mm', 'myanmar', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (180, 'kh', 'cambodia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (181, 'kh', 'cambodge', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (182, 'la', 'laos', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (183, 'in', 'india', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (184, 'in', 'inde', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (185, 'pk', 'pakistan', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (186, 'bd', 'bangladesh', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (187, 'lk', 'sri lanka', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (188, 'np', 'nepal', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (189, 'il', 'israel', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (190, 'lb', 'lebanon', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (191, 'lb', 'liban', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (192, 'jo', 'jordan', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (193, 'jo', 'jordanie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (194, 'iq', 'iraq', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (195, 'iq', 'irak', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (196, 'ir', 'iran', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197, 'sa', 'saudi arabia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (198, 'sa', 'arabie saoudite', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (199, 'ae', 'united arab emirates', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (200, 'ae', 'uae', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (201, 'ae', 'emirats arabes unis', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (202, 'qa', 'qatar', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (203, 'kw', 'kuwait', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (204, 'kw', 'koweit', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (205, 'om', 'oman', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (206, 'bh', 'bahrain', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (207, 'ps', 'palestine', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (208, 'sy', 'syria', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (209, 'sy', 'syrie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (210, 'ye', 'yemen', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (211, 'ma', 'morocco', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (212, 'ma', 'maroc', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (213, 'dz', 'algeria', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (214, 'dz', 'algerie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (215, 'tn', 'tunisia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (216, 'tn', 'tunisie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (217, 'eg', 'egypt', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (218, 'eg', 'egypte', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (219, 'ly', 'libya', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (220, 'ly', 'libye', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (221, 'za', 'south africa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (222, 'za', 'afrique du sud', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (223, 'ng', 'nigeria', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (224, 'ke', 'kenya', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (225, 'et', 'ethiopia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (226, 'et', 'ethiopie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (227, 'gh', 'ghana', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (228, 'sn', 'senegal', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (229, 'ci', 'ivory coast', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (230, 'ci', 'cote d''ivoire', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (231, 'ci', 'cote divoire', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (232, 'cm', 'cameroon', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (233, 'cm', 'cameroun', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (234, 'tz', 'tanzania', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (235, 'tz', 'tanzanie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (236, 'ug', 'uganda', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (237, 'ug', 'ouganda', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (238, 'mg', 'madagascar', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (239, 'cd', 'democratic republic of the congo', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (240, 'cd', 'dr congo', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (241, 'cd', 'rdc', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (242, 'cg', 'republic of the congo', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (243, 'cg', 'congo', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (244, 'bf', 'burkina faso', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (245, 'ml', 'mali', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (246, 'ne', 'niger', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (247, 'bj', 'benin', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (248, 'td', 'chad', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (249, 'td', 'tchad', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (250, 'rw', 'rwanda', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (251, 'mz', 'mozambique', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (252, 'zw', 'zimbabwe', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (253, 'mu', 'mauritius', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (254, 'mu', 'maurice', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (255, 'ga', 'gabon', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (256, 'tg', 'togo', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (257, 'au', 'australia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (258, 'au', 'australie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (259, 'nz', 'new zealand', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (260, 'nz', 'nouvelle-zelande', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (261, 'nz', 'nouvelle zelande', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (262, 'fj', 'fiji', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (263, 'fj', 'fidji', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (264, 'nc', 'new caledonia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (265, 'nc', 'nouvelle-caledonie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (266, 'nc', 'nouvelle caledonie', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (267, 'pf', 'french polynesia', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (268, 'pf', 'polynesie francaise', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (269, 'fr', 'guadeloupe', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (270, 'fr', 'martinique', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (271, 'fr', 'guyane', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (272, 'fr', 'reunion', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (273, 'fr', 'mayotte', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (274, 'fr', 'la reunion', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (275, 'fr', 'guyane francaise', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (276, 'fr', 'french guiana', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (277, 'hk', 'hong kong', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (278, 'us', 'u s a', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (279, 'us', 'ca usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (280, 'us', 'ma usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (281, 'us', 'ny usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (282, 'us', 'tx usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (283, 'us', 'pa usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (284, 'us', 'il usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (285, 'us', 'md usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (286, 'us', 'nc usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (287, 'us', 'ct usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (288, 'us', 'oh usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (289, 'us', 'va usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (290, 'us', 'nj usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (291, 'us', 'mi usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (292, 'us', 'wa usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (293, 'us', 'co usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (294, 'us', 'ga usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (295, 'us', 'fl usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (296, 'us', 'az usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (297, 'us', 'mn usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (298, 'us', 'mo usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (299, 'us', 'wi usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (300, 'us', 'tn usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (301, 'us', 'or usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (302, 'us', 'in usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (303, 'us', 'ia usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (304, 'us', 'nh usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (305, 'us', 'ri usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (306, 'us', 'sc usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (307, 'us', 'dc usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (308, 'us', 'ut usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (309, 'us', 'nm usa', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (310, 'cn', 'people s republic of china', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (311, 'cn', 'p r china', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (312, 'cn', 'prc', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (313, 'cn', 'pr of china', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (314, 'gb', 'north ireland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (315, 'gb', 'northern ireland', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (316, 'sg', 'rep of singapore', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (317, 'sk', 'slovak republic', 'country');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197738, 'hu', 'budapest', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197739, 'us', 'boston', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197740, 'it', 'roma', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197741, 'gb', 'london', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197742, 'nl', 'amsterdam', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197743, 'cz', 'prague', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197744, 'de', 'heidelberg', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197745, 'es', 'barcelona', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197746, 'us', 'chicago', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197747, 'cz', 'praha', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197748, 'it', 'milano', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197749, 'si', 'ljubljana', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197750, 'us', 'berkeley', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197751, 'cz', 'brno', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197752, 'it', 'firenze', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197753, 'us', 'ann arbor', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197754, 'nl', 'nijmegen', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197755, 'cn', 'shanghai', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197756, 'it', 'bologna', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197757, 'no', 'trondheim', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197758, 'ir', 'tehran', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197759, 'lb', 'beyrouth', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197760, 'it', 'milan italy', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197761, 'de', 'saarbrucken', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197762, 'us', 'gainesville', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197763, 'lb', 'beirut', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197764, 'us', 'santa barbara', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197766, 'it', 'rome italy', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197767, 'gb', 'sheffield', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197768, 'gb', 'bristol', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197769, 'gb', 'norwich', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197770, 'at', 'vienna austria', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197771, 'ma', 'oujda', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197772, 'dz', 'annaba', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197773, 'us', 'college park', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197774, 'cn', 'guangzhou', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197775, 'us', 'baltimore', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197776, 'ma', 'agdal', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197777, 'cn', 'hefei', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197778, 'cn', 'shenzhen', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197779, 'us', 'houston', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197781, 'jp', 'tokyo japan', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197782, 'us', 'albuquerque', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197783, 'be', 'leuven', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197784, 'be', 'brussels', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197785, 'se', 'goteborg', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197786, 'kr', 'seoul', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197787, 'de', 'darmstadt', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197788, 'be', 'bruxelles', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197789, 'us', 'fort collins', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197790, 'nl', 'leiden', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197791, 'us', 'bethesda', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197792, 'ma', 'marrakech', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197793, 'nl', 'wageningen', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197794, 'tr', 'istanbul', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197795, 'in', 'new delhi', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197796, 'cn', 'wuhan', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197797, 'sn', 'dakar', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197798, 'it', 'lecce', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197799, 'gb', 'southampton', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197800, 'ca', 'vancouver', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197801, 'ma', 'tetouan', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197802, 'us', 'new york ny', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197803, 'dz', 'tlemcen', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197804, 'us', 'austin', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197805, 'dk', 'aarhus', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197806, 'gb', 'leeds', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197808, 'us', 'portland', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197809, 'ch', 'basel', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197810, 'gb', 'york uk', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197811, 'au', 'brisbane', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197812, 'it', 'brescia', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197813, 'gb', 'newcastle', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197814, 'de', 'freiburg', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197815, 'es', 'pamplona', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197816, 'ru', 'moscow', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197817, 'at', 'innsbruck', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197818, 'de', 'bremen', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197819, 'us', 'philadelphia', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197820, 'es', 'santander', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197821, 'ma', 'ben guerir', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197822, 'at', 'vienne autriche', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197823, 'us', 'new brunswick', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197824, 'be', 'liege', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197825, 'fi', 'tampere', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197826, 'us', 'tallahassee', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197827, 'es', 'malaga', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197828, 'it', 'napoli', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197829, 'sa', 'riyadh', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197830, 'us', 'boston ma usa', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197831, 'de', 'dusseldorf', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197832, 'ma', 'agadir', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197833, 'de', 'leipzig', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197834, 'in', 'kolkata', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197835, 'tw', 'taipei taiwan', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197836, 'be', 'namur', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197837, 'tr', 'ankara', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197838, 'dz', 'sidi bel abbes', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197839, 'it', 'trieste', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197840, 'us', 'san francisco', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197841, 'in', 'bangalore', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197842, 'il', 'tel aviv', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197843, 'ch', 'dubendorf', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197844, 'cn', 'shangai', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197845, 'us', 'new york usa', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197846, 'pt', 'braga', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197847, 'gr', 'heraklion', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197848, 'lt', 'vilnius', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197849, 'it', 'padova', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197850, 'tn', 'manouba', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197851, 'us', 'east lansing', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197852, 'it', 'milan italie', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197853, 'tn', 'monastir', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197854, 'be', 'ghent', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197855, 'is', 'reykjavik', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197856, 'us', 'stanford', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197857, 'vn', 'hanoi', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197858, 'au', 'canberra', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197859, 'in', 'chennai', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197860, 'us', 'irvine', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197861, 'us', 'knoxville', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197862, 'us', 'oak ridge', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197863, 'us', 'twin cities', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197864, 'de', 'essen', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197865, 'cn', 'nanjing', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197866, 'us', 'urbana', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197868, 'nl', 'eindhoven', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197869, 'it', 'roma italia', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197870, 'pt', 'porto', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197871, 'ca', 'waterloo', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197872, 'us', 'nashville', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197873, 'rs', 'belgrade', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197874, 'jp', 'sendai', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197875, 'es', 'san sebastian', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197876, 'es', 'espainia', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197877, 'us', 'new haven', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197878, 'au', 'hobart', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197879, 'th', 'bangkok', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197880, 'ch', 'geneva', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197881, 'in', 'hyderabad', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197882, 'us', 'newark', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197883, 'cn', 'chengdu', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197884, 'ci', 'abidjan', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197885, 'ca', 'winnipeg', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197886, 'co', 'bogota', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197887, 'us', 'blacksburg', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197888, 'us', 'hampton', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197889, 'jp', 'osaka', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197890, 'us', 'atlanta ga', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197891, 'fr', 'poitiers', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197893, 'fr', 'dijon', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197894, 'fr', 'lyon', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197895, 'fr', 'strasbourg', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197898, 'fr', 'toulouse', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197899, 'fr', 'grenoble', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197900, 'fr', 'montpellier', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197901, 'fr', 'rouen', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197903, 'fr', 'nancy', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197904, 'fr', 'creteil', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197905, 'fr', 'palaiseau', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197911, 'fr', 'paris france', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197916, 'fr', 'chatillon', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197917, 'fr', 'reims', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197920, 'fr', 'caen', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197924, 'fr', 'villeurbanne', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197927, 'fr', 'occitanie', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197928, 'fr', 'pessac', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197931, 'fr', 'gif sur yvette', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197934, 'fr', 'suresnes', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197936, 'fr', 'amiens', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197937, 'fr', 'saint etienne', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197939, 'fr', 'limoges', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197940, 'fr', 'besancon', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197941, 'fr', 'orsay', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197942, 'fr', 'meudon', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197944, 'fr', 'bron', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197946, 'fr', 'saint martin d heres', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197947, 'fr', 'villenave d ornon', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197948, 'fr', 'bretigny sur orge', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197949, 'fr', 'villeneuve d ascq', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197951, 'fr', 'nouzilly', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197952, 'fr', 'saint herblain', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197955, 'fr', 'jouy en josas', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197956, 'fr', 'auzeville', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (197959, 'fr', 'marseille', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (235382, 'be', 'louvain', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (235385, 'cn', 'beijing', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (235386, 'fr', 'valenciennes', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (235387, 'fr', 'cachan', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (235388, 'ca', 'montreal', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (235390, 'fr', 'tourcoing', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (235391, 'fr', 'clermont ferrand', 'city');
INSERT INTO place_name_forms (id, iso_code, form_normalized, kind) VALUES (235392, 'by', 'republic of belarus', 'country');
SELECT setval(pg_get_serial_sequence('place_name_forms', 'id'), (SELECT COALESCE(MAX(id), 0) FROM place_name_forms));

COMMIT;
