"""Port : SQL de construction de la table `authorships`.

Implémenté par `infrastructure.db.queries.authorships_build.PgAuthorshipsBuildQueries`.
"""

from typing import Any, Protocol


class AuthorshipsBuildQueries(Protocol):
    """Opérations SQL pour promouvoir `source_authorships` → `authorships`."""

    def insert_missing_authorships(self, conn: Any) -> int: ...

    def link_source_authorships_to_authorship_for(self, conn: Any, source: str) -> int: ...

    def propagate_author_position(self, conn: Any) -> int: ...

    def propagate_is_corresponding(self, conn: Any) -> int: ...

    def propagate_roles(self, conn: Any) -> int: ...

    def reset_authorships_perimeter_and_structures(self, conn: Any) -> int: ...

    def propagate_perimeter_and_structures_from(self, conn: Any, source: str) -> int: ...

    def count_authorships_in_perimeter(self, conn: Any) -> int: ...
