"""Port : lectures pour `create_persons_from_source_authorships`.

Implémenté par `infrastructure.db.queries.persons_create.PgPersonsCreateQueries`.
"""

from typing import Any, Protocol


class PersonsCreateQueries(Protocol):
    """Opérations SQL pour le rattachement des authorships aux personnes."""

    def fetch_unlinked_hal_authorships(self, cur: Any) -> list[dict[str, Any]]: ...

    def fetch_unlinked_openalex_authorships(self, cur: Any) -> list[dict[str, Any]]: ...

    def fetch_unlinked_wos_authorships(self, cur: Any) -> list[dict[str, Any]]: ...

    def fetch_unlinked_scanr_authorships(self, cur: Any) -> list[dict[str, Any]]: ...

    def fetch_unlinked_theses_authorships(self, cur: Any) -> list[dict[str, Any]]: ...

    def fetch_linked_authorships_structured(self, cur: Any) -> list[dict[str, Any]]: ...

    def fetch_linked_authorships_openalex(self, cur: Any) -> list[dict[str, Any]]: ...

    def fetch_hal_account_to_person_map(self, cur: Any) -> dict[int, int]: ...

    def fetch_idref_to_person_map(self, cur: Any) -> dict[str, int]: ...

    def fetch_orcid_to_person_map(self, cur: Any) -> dict[str, int]: ...

    def fetch_name_form_map(self, cur: Any) -> dict[str, list[int]]: ...
