"""Modèles Pydantic des routers, regroupés par domaine fonctionnel.

Le découpage suit les routers (`interfaces/api/routers/*`). Pour éviter de
casser les imports historiques (`from interfaces.api.models import X`),
ce `__init__` re-expose toutes les classes au niveau du package.
"""

from interfaces.api.models._common import (
    BatchUpdatedResponse,
    CreatedIdResponse,
    DashboardOa,
    DeletedResponse,
    DetachedResponse,
    FacetValueCount,
    MergeRequest,
    MergeResponse,
    OkResponse,
    PubYearCount,
    RemovedResponse,
    StatusResponse,
    StructureRef,
    TotalCountResponse,
    ValueConfirmedOut,
    YesNoCount,
)
from interfaces.api.models.admin.addresses import (
    AddressPublicationsResponse,
    AddressReviewResponse,
    BatchCountryResponse,
    BatchReviewAction,
    BatchSetCountry,
    ReviewAction,
    SetCountry,
)
from interfaces.api.models.admin.authorships import (
    AssignOrphanAuthorship,
    AuthorshipExcludeResponse,
    BatchAssignOrphanAuthorships,
    CreatePersonName,
    ExcludeSourceAuthorship,
    ExcludeSourceAuthorshipResponse,
    OrphanAssignResponse,
    OrphanAuthorshipOut,
    OrphanAuthorshipsResponse,
    OrphanBatchAssignResponse,
    OrphanCountResponse,
    SourceAuthorshipRef,
)
from interfaces.api.models.admin.feedback import FeedbackStructuresResponse
from interfaces.api.models.admin.perimeters import (
    AddPerimeterStructure,
    PerimeterCreate,
    PerimeterUpdate,
)
from interfaces.api.models.admin.person_duplicates import (
    PersonConflictPairResponse,
    PersonDuplicatePairResponse,
)
from interfaces.api.models.admin.persons import (
    AddIdentifier,
    AddIdentifierResponse,
    DetachAuthorships,
    DetachAuthorshipsResponse,
    DetachNameForm,
    IdentifierReassignResponse,
    IdentifierStatusResponse,
    MarkPersonsDistinct,
    MergePersons,
    NameFormAuthorshipRef,
    NameFormAuthorshipsResponse,
    OtherPersonOut,
    ReassignIdentifier,
    RejectPerson,
    UpdateIdentifierStatus,
    UpdatePersonName,
)
from interfaces.api.models.admin.pipeline_config import (
    ConfigValueUpdate,
    HalCollectionsResponse,
)
from interfaces.api.models.admin.pipeline_logs import (
    PipelineLogsResponse,
    PipelineReportContent,
    PipelineReportItem,
    PipelineStatus,
)
from interfaces.api.models.admin.publication_duplicates import (
    MarkDistinctPublications,
    MergePublications,
    PubMergeResponse,
)
from interfaces.api.models.admin.structures import (
    NameFormCreate,
    NameFormUpdate,
    RelationCreate,
    StructureCreate,
    StructureRelationCreateResponse,
    StructureUpdate,
)
from interfaces.api.models.auth import AuthCheckResponse, LoginRequest
from interfaces.api.models.journals import JournalUpdate
from interfaces.api.models.persons import (
    DepartmentCount,
    NameFormSummaryOut,
    PersonAddressesResponse,
    PersonAddressOut,
    PersonAddressStruct,
    PersonDashboardResponse,
    PersonDirectoryEntry,
    PersonDirectoryResponse,
    PersonIdentifierOut,
    PersonListResponse,
    PersonOut,
    PersonProfileAuthor,
    PersonProfileCore,
    PersonProfileResponse,
    PersonSearchResult,
    PersonsFacetsResponse,
    PersonsStatsResponse,
    PersonThesesResponse,
    PersonThesesSection,
    PersonThesis,
    RoleCount,
)
from interfaces.api.models.publishers import PublisherUpdate

__all__ = [
    "AddIdentifier",
    "AddIdentifierResponse",
    "AddPerimeterStructure",
    "AddressPublicationsResponse",
    "AddressReviewResponse",
    "AssignOrphanAuthorship",
    "AuthCheckResponse",
    "AuthorshipExcludeResponse",
    "BatchAssignOrphanAuthorships",
    "BatchCountryResponse",
    "BatchReviewAction",
    "BatchSetCountry",
    "BatchUpdatedResponse",
    "ConfigValueUpdate",
    "CreatePersonName",
    "CreatedIdResponse",
    "DashboardOa",
    "DeletedResponse",
    "DepartmentCount",
    "DetachAuthorships",
    "DetachAuthorshipsResponse",
    "DetachNameForm",
    "DetachedResponse",
    "ExcludeSourceAuthorship",
    "ExcludeSourceAuthorshipResponse",
    "FacetValueCount",
    "FeedbackStructuresResponse",
    "HalCollectionsResponse",
    "IdentifierReassignResponse",
    "IdentifierStatusResponse",
    "JournalUpdate",
    "LoginRequest",
    "MarkDistinctPublications",
    "MarkPersonsDistinct",
    "MarkDistinctPublications",
    "MergePersons",
    "MergePublications",
    "MergeRequest",
    "MergeResponse",
    "NameFormAuthorshipRef",
    "NameFormAuthorshipsResponse",
    "NameFormCreate",
    "NameFormSummaryOut",
    "NameFormUpdate",
    "OkResponse",
    "OrphanAssignResponse",
    "OrphanAuthorshipOut",
    "OrphanAuthorshipsResponse",
    "OrphanBatchAssignResponse",
    "OrphanCountResponse",
    "OtherPersonOut",
    "PerimeterCreate",
    "PerimeterUpdate",
    "PersonAddressOut",
    "PersonAddressStruct",
    "PersonAddressesResponse",
    "PersonConflictPairResponse",
    "PersonDashboardResponse",
    "PersonDirectoryEntry",
    "PersonDirectoryResponse",
    "PersonDuplicatePairResponse",
    "PersonIdentifierOut",
    "PersonListResponse",
    "PersonOut",
    "PersonProfileAuthor",
    "PersonProfileCore",
    "PersonProfileResponse",
    "PersonSearchResult",
    "PersonThesesResponse",
    "PersonThesesSection",
    "PersonThesis",
    "PersonsFacetsResponse",
    "PersonsStatsResponse",
    "PipelineLogsResponse",
    "PipelineReportContent",
    "PipelineReportItem",
    "PipelineStatus",
    "PubMergeResponse",
    "PubYearCount",
    "PublisherUpdate",
    "ReassignIdentifier",
    "RejectPerson",
    "RelationCreate",
    "RemovedResponse",
    "ReviewAction",
    "RoleCount",
    "SetCountry",
    "SourceAuthorshipRef",
    "StatusResponse",
    "StructureCreate",
    "StructureRef",
    "StructureRelationCreateResponse",
    "StructureUpdate",
    "TotalCountResponse",
    "UpdateIdentifierStatus",
    "UpdatePersonName",
    "ValueConfirmedOut",
    "YesNoCount",
]
